// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: task.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Task_CreateTask_FullMethodName               = "/task.Task/CreateTask"
	Task_ListTeamTasks_FullMethodName            = "/task.Task/ListTeamTasks"
	Task_SetTaskStatus_FullMethodName            = "/task.Task/SetTaskStatus"
	Task_ListTaskNotifications_FullMethodName    = "/task.Task/ListTaskNotifications"
	Task_MarkTaskNotificationRead_FullMethodName = "/task.Task/MarkTaskNotificationRead"
	Task_ListMyTasks_FullMethodName              = "/task.Task/ListMyTasks"
	Task_GetTask_FullMethodName                  = "/task.Task/GetTask"
	Task_ListMyTaskNotifications_FullMethodName  = "/task.Task/ListMyTaskNotifications"
)

// TaskClient is the client API for Task service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskClient interface {
	// authorization 和 idempotency-key 经 gRPC metadata 传入。
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	// authorization 经 gRPC metadata 传入；先核对当前团队成员资格。
	ListTeamTasks(ctx context.Context, in *ListTeamTasksRequest, opts ...grpc.CallOption) (*ListTeamTasksResponse, error)
	// authorization 经 gRPC metadata 传入；仅创建者、负责人或团队拥有者可改状态。
	SetTaskStatus(ctx context.Context, in *SetTaskStatusRequest, opts ...grpc.CallOption) (*SetTaskStatusResponse, error)
	// authorization 经 gRPC metadata 传入；只列当前团队中自己的通知。
	ListTaskNotifications(ctx context.Context, in *ListTaskNotificationsRequest, opts ...grpc.CallOption) (*ListTaskNotificationsResponse, error)
	// 本人显式确认；只更新当前团队中自己的通知，重复确认保留首次时间。
	MarkTaskNotificationRead(ctx context.Context, in *MarkTaskNotificationReadRequest, opts ...grpc.CallOption) (*MarkTaskNotificationReadResponse, error)
	// 本人跨当前活动团队读取分配给自己的任务；不接受客户端 user_id。
	ListMyTasks(ctx context.Context, in *ListMyTasksRequest, opts ...grpc.CallOption) (*ListMyTasksResponse, error)
	// 当前团队成员按团队与任务 ID 恢复详情，并返回服务端计算的状态更新资格。
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	// 本人跨当前活动团队读取持久任务通知与权威未读总数。
	ListMyTaskNotifications(ctx context.Context, in *ListMyTaskNotificationsRequest, opts ...grpc.CallOption) (*ListMyTaskNotificationsResponse, error)
}

type taskClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskClient(cc grpc.ClientConnInterface) TaskClient {
	return &taskClient{cc}
}

func (c *taskClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, Task_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) ListTeamTasks(ctx context.Context, in *ListTeamTasksRequest, opts ...grpc.CallOption) (*ListTeamTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTeamTasksResponse)
	err := c.cc.Invoke(ctx, Task_ListTeamTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) SetTaskStatus(ctx context.Context, in *SetTaskStatusRequest, opts ...grpc.CallOption) (*SetTaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTaskStatusResponse)
	err := c.cc.Invoke(ctx, Task_SetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) ListTaskNotifications(ctx context.Context, in *ListTaskNotificationsRequest, opts ...grpc.CallOption) (*ListTaskNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaskNotificationsResponse)
	err := c.cc.Invoke(ctx, Task_ListTaskNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) MarkTaskNotificationRead(ctx context.Context, in *MarkTaskNotificationReadRequest, opts ...grpc.CallOption) (*MarkTaskNotificationReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkTaskNotificationReadResponse)
	err := c.cc.Invoke(ctx, Task_MarkTaskNotificationRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) ListMyTasks(ctx context.Context, in *ListMyTasksRequest, opts ...grpc.CallOption) (*ListMyTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyTasksResponse)
	err := c.cc.Invoke(ctx, Task_ListMyTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, Task_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) ListMyTaskNotifications(ctx context.Context, in *ListMyTaskNotificationsRequest, opts ...grpc.CallOption) (*ListMyTaskNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyTaskNotificationsResponse)
	err := c.cc.Invoke(ctx, Task_ListMyTaskNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServer is the server API for Task service.
// All implementations must embed UnimplementedTaskServer
// for forward compatibility.
type TaskServer interface {
	// authorization 和 idempotency-key 经 gRPC metadata 传入。
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	// authorization 经 gRPC metadata 传入；先核对当前团队成员资格。
	ListTeamTasks(context.Context, *ListTeamTasksRequest) (*ListTeamTasksResponse, error)
	// authorization 经 gRPC metadata 传入；仅创建者、负责人或团队拥有者可改状态。
	SetTaskStatus(context.Context, *SetTaskStatusRequest) (*SetTaskStatusResponse, error)
	// authorization 经 gRPC metadata 传入；只列当前团队中自己的通知。
	ListTaskNotifications(context.Context, *ListTaskNotificationsRequest) (*ListTaskNotificationsResponse, error)
	// 本人显式确认；只更新当前团队中自己的通知，重复确认保留首次时间。
	MarkTaskNotificationRead(context.Context, *MarkTaskNotificationReadRequest) (*MarkTaskNotificationReadResponse, error)
	// 本人跨当前活动团队读取分配给自己的任务；不接受客户端 user_id。
	ListMyTasks(context.Context, *ListMyTasksRequest) (*ListMyTasksResponse, error)
	// 当前团队成员按团队与任务 ID 恢复详情，并返回服务端计算的状态更新资格。
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	// 本人跨当前活动团队读取持久任务通知与权威未读总数。
	ListMyTaskNotifications(context.Context, *ListMyTaskNotificationsRequest) (*ListMyTaskNotificationsResponse, error)
	mustEmbedUnimplementedTaskServer()
}

// UnimplementedTaskServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServer struct{}

func (UnimplementedTaskServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTaskServer) ListTeamTasks(context.Context, *ListTeamTasksRequest) (*ListTeamTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTeamTasks not implemented")
}
func (UnimplementedTaskServer) SetTaskStatus(context.Context, *SetTaskStatusRequest) (*SetTaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTaskStatus not implemented")
}
func (UnimplementedTaskServer) ListTaskNotifications(context.Context, *ListTaskNotificationsRequest) (*ListTaskNotificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTaskNotifications not implemented")
}
func (UnimplementedTaskServer) MarkTaskNotificationRead(context.Context, *MarkTaskNotificationReadRequest) (*MarkTaskNotificationReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkTaskNotificationRead not implemented")
}
func (UnimplementedTaskServer) ListMyTasks(context.Context, *ListMyTasksRequest) (*ListMyTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyTasks not implemented")
}
func (UnimplementedTaskServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskServer) ListMyTaskNotifications(context.Context, *ListMyTaskNotificationsRequest) (*ListMyTaskNotificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyTaskNotifications not implemented")
}
func (UnimplementedTaskServer) mustEmbedUnimplementedTaskServer() {}
func (UnimplementedTaskServer) testEmbeddedByValue()              {}

// UnsafeTaskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServer will
// result in compilation errors.
type UnsafeTaskServer interface {
	mustEmbedUnimplementedTaskServer()
}

func RegisterTaskServer(s grpc.ServiceRegistrar, srv TaskServer) {
	// If the following call pancis, it indicates UnimplementedTaskServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Task_ServiceDesc, srv)
}

func _Task_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_ListTeamTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).ListTeamTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_ListTeamTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).ListTeamTasks(ctx, req.(*ListTeamTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_SetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).SetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_SetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).SetTaskStatus(ctx, req.(*SetTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_ListTaskNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).ListTaskNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_ListTaskNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).ListTaskNotifications(ctx, req.(*ListTaskNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_MarkTaskNotificationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkTaskNotificationReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).MarkTaskNotificationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_MarkTaskNotificationRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).MarkTaskNotificationRead(ctx, req.(*MarkTaskNotificationReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_ListMyTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).ListMyTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_ListMyTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).ListMyTasks(ctx, req.(*ListMyTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_ListMyTaskNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyTaskNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).ListMyTaskNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Task_ListMyTaskNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).ListMyTaskNotifications(ctx, req.(*ListMyTaskNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Task_ServiceDesc is the grpc.ServiceDesc for Task service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Task_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.Task",
	HandlerType: (*TaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _Task_CreateTask_Handler,
		},
		{
			MethodName: "ListTeamTasks",
			Handler:    _Task_ListTeamTasks_Handler,
		},
		{
			MethodName: "SetTaskStatus",
			Handler:    _Task_SetTaskStatus_Handler,
		},
		{
			MethodName: "ListTaskNotifications",
			Handler:    _Task_ListTaskNotifications_Handler,
		},
		{
			MethodName: "MarkTaskNotificationRead",
			Handler:    _Task_MarkTaskNotificationRead_Handler,
		},
		{
			MethodName: "ListMyTasks",
			Handler:    _Task_ListMyTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Task_GetTask_Handler,
		},
		{
			MethodName: "ListMyTaskNotifications",
			Handler:    _Task_ListMyTaskNotifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
