// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: rpc/im/bot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostTaskCreatedCardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A persisted Agent run. IM derives the stable message ID from this value.
	RunId   int64 `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TeamId  int64 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId int64 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Versioned result from a confirmed draft and actual Task success.
	Content       string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // No bot ID or user ID: IM determines both from trusted context/configuration.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTaskCreatedCardRequest) Reset() {
	*x = PostTaskCreatedCardRequest{}
	mi := &file_rpc_im_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTaskCreatedCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTaskCreatedCardRequest) ProtoMessage() {}

func (x *PostTaskCreatedCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTaskCreatedCardRequest.ProtoReflect.Descriptor instead.
func (*PostTaskCreatedCardRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_bot_proto_rawDescGZIP(), []int{0}
}

func (x *PostTaskCreatedCardRequest) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *PostTaskCreatedCardRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *PostTaskCreatedCardRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *PostTaskCreatedCardRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PostTaskCreatedCardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MsgId string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// True only after Kafka acknowledgement and persistence of that acknowledgement.
	// This is not a history-persistence or member-delivery receipt.
	Accepted      bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTaskCreatedCardResponse) Reset() {
	*x = PostTaskCreatedCardResponse{}
	mi := &file_rpc_im_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTaskCreatedCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTaskCreatedCardResponse) ProtoMessage() {}

func (x *PostTaskCreatedCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTaskCreatedCardResponse.ProtoReflect.Descriptor instead.
func (*PostTaskCreatedCardResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_bot_proto_rawDescGZIP(), []int{1}
}

func (x *PostTaskCreatedCardResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *PostTaskCreatedCardResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type PostTaskCreatedCardItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId int64                  `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Required presence; stable zero-based index in the persisted Agent collection (0..4).
	ItemIndex *int32 `protobuf:"varint,2,opt,name=item_index,json=itemIndex,proto3,oneof" json:"item_index,omitempty"`
	TeamId    int64  `protobuf:"varint,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId   int64  `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Same version-1 card as the original single-item method.
	Content       string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTaskCreatedCardItemRequest) Reset() {
	*x = PostTaskCreatedCardItemRequest{}
	mi := &file_rpc_im_bot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTaskCreatedCardItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTaskCreatedCardItemRequest) ProtoMessage() {}

func (x *PostTaskCreatedCardItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_bot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTaskCreatedCardItemRequest.ProtoReflect.Descriptor instead.
func (*PostTaskCreatedCardItemRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_bot_proto_rawDescGZIP(), []int{2}
}

func (x *PostTaskCreatedCardItemRequest) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *PostTaskCreatedCardItemRequest) GetItemIndex() int32 {
	if x != nil && x.ItemIndex != nil {
		return *x.ItemIndex
	}
	return 0
}

func (x *PostTaskCreatedCardItemRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *PostTaskCreatedCardItemRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *PostTaskCreatedCardItemRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_rpc_im_bot_proto protoreflect.FileDescriptor

const file_rpc_im_bot_proto_rawDesc = "" +
	"\n" +
	"\x10rpc/im/bot.proto\x12\x02im\"\x81\x01\n" +
	"\x1aPostTaskCreatedCardRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x03R\x05runId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"P\n" +
	"\x1bPostTaskCreatedCardResponse\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\"\xb8\x01\n" +
	"\x1ePostTaskCreatedCardItemRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x03R\x05runId\x12\"\n" +
	"\n" +
	"item_index\x18\x02 \x01(\x05H\x00R\titemIndex\x88\x01\x01\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\x03R\agroupId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontentB\r\n" +
	"\v_item_index2\xbf\x01\n" +
	"\x05IMBot\x12V\n" +
	"\x13PostTaskCreatedCard\x12\x1e.im.PostTaskCreatedCardRequest\x1a\x1f.im.PostTaskCreatedCardResponse\x12^\n" +
	"\x17PostTaskCreatedCardItem\x12\".im.PostTaskCreatedCardItemRequest\x1a\x1f.im.PostTaskCreatedCardResponseB$Z\"github.com/yjydist/go-im/rpc/im/pbb\x06proto3"

var (
	file_rpc_im_bot_proto_rawDescOnce sync.Once
	file_rpc_im_bot_proto_rawDescData []byte
)

func file_rpc_im_bot_proto_rawDescGZIP() []byte {
	file_rpc_im_bot_proto_rawDescOnce.Do(func() {
		file_rpc_im_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_im_bot_proto_rawDesc), len(file_rpc_im_bot_proto_rawDesc)))
	})
	return file_rpc_im_bot_proto_rawDescData
}

var file_rpc_im_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_im_bot_proto_goTypes = []any{
	(*PostTaskCreatedCardRequest)(nil),     // 0: im.PostTaskCreatedCardRequest
	(*PostTaskCreatedCardResponse)(nil),    // 1: im.PostTaskCreatedCardResponse
	(*PostTaskCreatedCardItemRequest)(nil), // 2: im.PostTaskCreatedCardItemRequest
}
var file_rpc_im_bot_proto_depIdxs = []int32{
	0, // 0: im.IMBot.PostTaskCreatedCard:input_type -> im.PostTaskCreatedCardRequest
	2, // 1: im.IMBot.PostTaskCreatedCardItem:input_type -> im.PostTaskCreatedCardItemRequest
	1, // 2: im.IMBot.PostTaskCreatedCard:output_type -> im.PostTaskCreatedCardResponse
	1, // 3: im.IMBot.PostTaskCreatedCardItem:output_type -> im.PostTaskCreatedCardResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_im_bot_proto_init() }
func file_rpc_im_bot_proto_init() {
	if File_rpc_im_bot_proto != nil {
		return
	}
	file_rpc_im_bot_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_im_bot_proto_rawDesc), len(file_rpc_im_bot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_im_bot_proto_goTypes,
		DependencyIndexes: file_rpc_im_bot_proto_depIdxs,
		MessageInfos:      file_rpc_im_bot_proto_msgTypes,
	}.Build()
	File_rpc_im_bot_proto = out.File
	file_rpc_im_bot_proto_goTypes = nil
	file_rpc_im_bot_proto_depIdxs = nil
}
