// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: rpc/im/bot.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IMBot_PostTaskCreatedCard_FullMethodName     = "/im.IMBot/PostTaskCreatedCard"
	IMBot_PostTaskCreatedCardItem_FullMethodName = "/im.IMBot/PostTaskCreatedCardItem"
)

// IMBotClient is the client API for IMBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Registered only on IM's dedicated mutual-TLS listener, never the ordinary IM port.
type IMBotClient interface {
	PostTaskCreatedCard(ctx context.Context, in *PostTaskCreatedCardRequest, opts ...grpc.CallOption) (*PostTaskCreatedCardResponse, error)
	// Separate method prevents older IM servers silently treating every item as item 0.
	PostTaskCreatedCardItem(ctx context.Context, in *PostTaskCreatedCardItemRequest, opts ...grpc.CallOption) (*PostTaskCreatedCardResponse, error)
}

type iMBotClient struct {
	cc grpc.ClientConnInterface
}

func NewIMBotClient(cc grpc.ClientConnInterface) IMBotClient {
	return &iMBotClient{cc}
}

func (c *iMBotClient) PostTaskCreatedCard(ctx context.Context, in *PostTaskCreatedCardRequest, opts ...grpc.CallOption) (*PostTaskCreatedCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostTaskCreatedCardResponse)
	err := c.cc.Invoke(ctx, IMBot_PostTaskCreatedCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMBotClient) PostTaskCreatedCardItem(ctx context.Context, in *PostTaskCreatedCardItemRequest, opts ...grpc.CallOption) (*PostTaskCreatedCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostTaskCreatedCardResponse)
	err := c.cc.Invoke(ctx, IMBot_PostTaskCreatedCardItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMBotServer is the server API for IMBot service.
// All implementations must embed UnimplementedIMBotServer
// for forward compatibility.
//
// Registered only on IM's dedicated mutual-TLS listener, never the ordinary IM port.
type IMBotServer interface {
	PostTaskCreatedCard(context.Context, *PostTaskCreatedCardRequest) (*PostTaskCreatedCardResponse, error)
	// Separate method prevents older IM servers silently treating every item as item 0.
	PostTaskCreatedCardItem(context.Context, *PostTaskCreatedCardItemRequest) (*PostTaskCreatedCardResponse, error)
	mustEmbedUnimplementedIMBotServer()
}

// UnimplementedIMBotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIMBotServer struct{}

func (UnimplementedIMBotServer) PostTaskCreatedCard(context.Context, *PostTaskCreatedCardRequest) (*PostTaskCreatedCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTaskCreatedCard not implemented")
}
func (UnimplementedIMBotServer) PostTaskCreatedCardItem(context.Context, *PostTaskCreatedCardItemRequest) (*PostTaskCreatedCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTaskCreatedCardItem not implemented")
}
func (UnimplementedIMBotServer) mustEmbedUnimplementedIMBotServer() {}
func (UnimplementedIMBotServer) testEmbeddedByValue()               {}

// UnsafeIMBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMBotServer will
// result in compilation errors.
type UnsafeIMBotServer interface {
	mustEmbedUnimplementedIMBotServer()
}

func RegisterIMBotServer(s grpc.ServiceRegistrar, srv IMBotServer) {
	// If the following call pancis, it indicates UnimplementedIMBotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IMBot_ServiceDesc, srv)
}

func _IMBot_PostTaskCreatedCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTaskCreatedCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMBotServer).PostTaskCreatedCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMBot_PostTaskCreatedCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMBotServer).PostTaskCreatedCard(ctx, req.(*PostTaskCreatedCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMBot_PostTaskCreatedCardItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTaskCreatedCardItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMBotServer).PostTaskCreatedCardItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMBot_PostTaskCreatedCardItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMBotServer).PostTaskCreatedCardItem(ctx, req.(*PostTaskCreatedCardItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IMBot_ServiceDesc is the grpc.ServiceDesc for IMBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "im.IMBot",
	HandlerType: (*IMBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostTaskCreatedCard",
			Handler:    _IMBot_PostTaskCreatedCard_Handler,
		},
		{
			MethodName: "PostTaskCreatedCardItem",
			Handler:    _IMBot_PostTaskCreatedCardItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/im/bot.proto",
}
