// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: rpc/im/im.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckOfflineMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageIds    []int64                `protobuf:"varint,1,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckOfflineMessagesRequest) Reset() {
	*x = AckOfflineMessagesRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckOfflineMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckOfflineMessagesRequest) ProtoMessage() {}

func (x *AckOfflineMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckOfflineMessagesRequest.ProtoReflect.Descriptor instead.
func (*AckOfflineMessagesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{0}
}

func (x *AckOfflineMessagesRequest) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type AckOfflineMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckOfflineMessagesResponse) Reset() {
	*x = AckOfflineMessagesResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckOfflineMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckOfflineMessagesResponse) ProtoMessage() {}

func (x *AckOfflineMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckOfflineMessagesResponse.ProtoReflect.Descriptor instead.
func (*AckOfflineMessagesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{1}
}

type ListOfflineMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOfflineMessagesRequest) Reset() {
	*x = ListOfflineMessagesRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOfflineMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfflineMessagesRequest) ProtoMessage() {}

func (x *ListOfflineMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfflineMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListOfflineMessagesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{2}
}

type OfflineMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgId       string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	FromId      int64                  `protobuf:"varint,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId        int64                  `protobuf:"varint,4,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ChatType    int32                  `protobuf:"varint,5,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`
	ContentType int32                  `protobuf:"varint,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content     string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 1: user, 2: IM bot; 0 means a legacy user message.
	SenderType    int32 `protobuf:"varint,9,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	InitiatorId   int64 `protobuf:"varint,10,opt,name=initiator_id,json=initiatorId,proto3" json:"initiator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineMessage) Reset() {
	*x = OfflineMessage{}
	mi := &file_rpc_im_im_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineMessage) ProtoMessage() {}

func (x *OfflineMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineMessage.ProtoReflect.Descriptor instead.
func (*OfflineMessage) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{3}
}

func (x *OfflineMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OfflineMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *OfflineMessage) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *OfflineMessage) GetToId() int64 {
	if x != nil {
		return x.ToId
	}
	return 0
}

func (x *OfflineMessage) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *OfflineMessage) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *OfflineMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *OfflineMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OfflineMessage) GetSenderType() int32 {
	if x != nil {
		return x.SenderType
	}
	return 0
}

func (x *OfflineMessage) GetInitiatorId() int64 {
	if x != nil {
		return x.InitiatorId
	}
	return 0
}

type ListOfflineMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*OfflineMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOfflineMessagesResponse) Reset() {
	*x = ListOfflineMessagesResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOfflineMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfflineMessagesResponse) ProtoMessage() {}

func (x *ListOfflineMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfflineMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListOfflineMessagesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{4}
}

func (x *ListOfflineMessagesResponse) GetMessages() []*OfflineMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ListTeamGroupMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TeamId          int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId         int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	BeforeMessageId int64                  `protobuf:"varint,3,opt,name=before_message_id,json=beforeMessageId,proto3" json:"before_message_id,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListTeamGroupMessagesRequest) Reset() {
	*x = ListTeamGroupMessagesRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamGroupMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamGroupMessagesRequest) ProtoMessage() {}

func (x *ListTeamGroupMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamGroupMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListTeamGroupMessagesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{5}
}

func (x *ListTeamGroupMessagesRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ListTeamGroupMessagesRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListTeamGroupMessagesRequest) GetBeforeMessageId() int64 {
	if x != nil {
		return x.BeforeMessageId
	}
	return 0
}

func (x *ListTeamGroupMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TeamGroupMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgId           string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	FromId          int64                  `protobuf:"varint,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ContentType     int32                  `protobuf:"varint,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content         string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,6,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	// from_id refers to a user or bot according to sender_type.
	SenderType    int32 `protobuf:"varint,7,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	InitiatorId   int64 `protobuf:"varint,8,opt,name=initiator_id,json=initiatorId,proto3" json:"initiator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamGroupMessage) Reset() {
	*x = TeamGroupMessage{}
	mi := &file_rpc_im_im_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamGroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamGroupMessage) ProtoMessage() {}

func (x *TeamGroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamGroupMessage.ProtoReflect.Descriptor instead.
func (*TeamGroupMessage) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{6}
}

func (x *TeamGroupMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TeamGroupMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *TeamGroupMessage) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *TeamGroupMessage) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *TeamGroupMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TeamGroupMessage) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *TeamGroupMessage) GetSenderType() int32 {
	if x != nil {
		return x.SenderType
	}
	return 0
}

func (x *TeamGroupMessage) GetInitiatorId() int64 {
	if x != nil {
		return x.InitiatorId
	}
	return 0
}

type ListTeamGroupMessagesResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Messages            []*TeamGroupMessage    `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextBeforeMessageId int64                  `protobuf:"varint,2,opt,name=next_before_message_id,json=nextBeforeMessageId,proto3" json:"next_before_message_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListTeamGroupMessagesResponse) Reset() {
	*x = ListTeamGroupMessagesResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamGroupMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamGroupMessagesResponse) ProtoMessage() {}

func (x *ListTeamGroupMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamGroupMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListTeamGroupMessagesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{7}
}

func (x *ListTeamGroupMessagesResponse) GetMessages() []*TeamGroupMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListTeamGroupMessagesResponse) GetNextBeforeMessageId() int64 {
	if x != nil {
		return x.NextBeforeMessageId
	}
	return 0
}

type CheckTeamGroupMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamGroupMessageRequest) Reset() {
	*x = CheckTeamGroupMessageRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamGroupMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamGroupMessageRequest) ProtoMessage() {}

func (x *CheckTeamGroupMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamGroupMessageRequest.ProtoReflect.Descriptor instead.
func (*CheckTeamGroupMessageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{8}
}

func (x *CheckTeamGroupMessageRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CheckTeamGroupMessageRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CheckTeamGroupMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type CheckTeamGroupMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamGroupMessageResponse) Reset() {
	*x = CheckTeamGroupMessageResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamGroupMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamGroupMessageResponse) ProtoMessage() {}

func (x *CheckTeamGroupMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamGroupMessageResponse.ProtoReflect.Descriptor instead.
func (*CheckTeamGroupMessageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{9}
}

type JoinTeamGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTeamGroupRequest) Reset() {
	*x = JoinTeamGroupRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTeamGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTeamGroupRequest) ProtoMessage() {}

func (x *JoinTeamGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTeamGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinTeamGroupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{10}
}

func (x *JoinTeamGroupRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *JoinTeamGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type JoinTeamGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTeamGroupResponse) Reset() {
	*x = JoinTeamGroupResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTeamGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTeamGroupResponse) ProtoMessage() {}

func (x *JoinTeamGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTeamGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinTeamGroupResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{11}
}

type ListTeamGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	AfterGroupId  int64                  `protobuf:"varint,2,opt,name=after_group_id,json=afterGroupId,proto3" json:"after_group_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamGroupsRequest) Reset() {
	*x = ListTeamGroupsRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamGroupsRequest) ProtoMessage() {}

func (x *ListTeamGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamGroupsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{12}
}

func (x *ListTeamGroupsRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ListTeamGroupsRequest) GetAfterGroupId() int64 {
	if x != nil {
		return x.AfterGroupId
	}
	return 0
}

func (x *ListTeamGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TeamGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamGroup) Reset() {
	*x = TeamGroup{}
	mi := &file_rpc_im_im_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamGroup) ProtoMessage() {}

func (x *TeamGroup) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamGroup.ProtoReflect.Descriptor instead.
func (*TeamGroup) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{13}
}

func (x *TeamGroup) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *TeamGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeamGroup) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type ListTeamGroupsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Groups           []*TeamGroup           `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	NextAfterGroupId int64                  `protobuf:"varint,2,opt,name=next_after_group_id,json=nextAfterGroupId,proto3" json:"next_after_group_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTeamGroupsResponse) Reset() {
	*x = ListTeamGroupsResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamGroupsResponse) ProtoMessage() {}

func (x *ListTeamGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamGroupsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{14}
}

func (x *ListTeamGroupsResponse) GetGroups() []*TeamGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListTeamGroupsResponse) GetNextAfterGroupId() int64 {
	if x != nil {
		return x.NextAfterGroupId
	}
	return 0
}

type CreateTeamGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamGroupRequest) Reset() {
	*x = CreateTeamGroupRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamGroupRequest) ProtoMessage() {}

func (x *CreateTeamGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamGroupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{15}
}

func (x *CreateTeamGroupRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CreateTeamGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTeamGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamGroupResponse) Reset() {
	*x = CreateTeamGroupResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamGroupResponse) ProtoMessage() {}

func (x *CreateTeamGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamGroupResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{16}
}

func (x *CreateTeamGroupResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type CheckGroupMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckGroupMemberRequest) Reset() {
	*x = CheckGroupMemberRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGroupMemberRequest) ProtoMessage() {}

func (x *CheckGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*CheckGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{17}
}

func (x *CheckGroupMemberRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type CheckGroupMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckGroupMemberResponse) Reset() {
	*x = CheckGroupMemberResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGroupMemberResponse) ProtoMessage() {}

func (x *CheckGroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGroupMemberResponse.ProtoReflect.Descriptor instead.
func (*CheckGroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{18}
}

type CheckTeamGroupAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamGroupAccessRequest) Reset() {
	*x = CheckTeamGroupAccessRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamGroupAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamGroupAccessRequest) ProtoMessage() {}

func (x *CheckTeamGroupAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamGroupAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckTeamGroupAccessRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{19}
}

func (x *CheckTeamGroupAccessRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CheckTeamGroupAccessRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type CheckTeamGroupAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamGroupAccessResponse) Reset() {
	*x = CheckTeamGroupAccessResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamGroupAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamGroupAccessResponse) ProtoMessage() {}

func (x *CheckTeamGroupAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamGroupAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckTeamGroupAccessResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{20}
}

var File_rpc_im_im_proto protoreflect.FileDescriptor

const file_rpc_im_im_proto_rawDesc = "" +
	"\n" +
	"\x0frpc/im/im.proto\x12\x02im\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\x19AckOfflineMessagesRequest\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\x03R\n" +
	"messageIds\"\x1c\n" +
	"\x1aAckOfflineMessagesResponse\"\x1c\n" +
	"\x1aListOfflineMessagesRequest\"\xbe\x02\n" +
	"\x0eOfflineMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x17\n" +
	"\afrom_id\x18\x03 \x01(\x03R\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x04 \x01(\x03R\x04toId\x12\x1b\n" +
	"\tchat_type\x18\x05 \x01(\x05R\bchatType\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\x05R\vcontentType\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vsender_type\x18\t \x01(\x05R\n" +
	"senderType\x12!\n" +
	"\finitiator_id\x18\n" +
	" \x01(\x03R\vinitiatorId\"M\n" +
	"\x1bListOfflineMessagesResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.im.OfflineMessageR\bmessages\"\x94\x01\n" +
	"\x1cListTeamGroupMessagesRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12*\n" +
	"\x11before_message_id\x18\x03 \x01(\x03R\x0fbeforeMessageId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x80\x02\n" +
	"\x10TeamGroupMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x17\n" +
	"\afrom_id\x18\x03 \x01(\x03R\x06fromId\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\x05R\vcontentType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12+\n" +
	"\x12created_at_unix_ms\x18\x06 \x01(\x03R\x0fcreatedAtUnixMs\x12\x1f\n" +
	"\vsender_type\x18\a \x01(\x05R\n" +
	"senderType\x12!\n" +
	"\finitiator_id\x18\b \x01(\x03R\vinitiatorId\"\x86\x01\n" +
	"\x1dListTeamGroupMessagesResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.im.TeamGroupMessageR\bmessages\x123\n" +
	"\x16next_before_message_id\x18\x02 \x01(\x03R\x13nextBeforeMessageId\"q\n" +
	"\x1cCheckTeamGroupMessageRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\"\x1f\n" +
	"\x1dCheckTeamGroupMessageResponse\"J\n" +
	"\x14JoinTeamGroupRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\"\x17\n" +
	"\x15JoinTeamGroupResponse\"l\n" +
	"\x15ListTeamGroupsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12$\n" +
	"\x0eafter_group_id\x18\x02 \x01(\x03R\fafterGroupId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"U\n" +
	"\tTeamGroup\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\"n\n" +
	"\x16ListTeamGroupsResponse\x12%\n" +
	"\x06groups\x18\x01 \x03(\v2\r.im.TeamGroupR\x06groups\x12-\n" +
	"\x13next_after_group_id\x18\x02 \x01(\x03R\x10nextAfterGroupId\"E\n" +
	"\x16CreateTeamGroupRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"4\n" +
	"\x17CreateTeamGroupResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"4\n" +
	"\x17CheckGroupMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"\x1a\n" +
	"\x18CheckGroupMemberResponse\"Q\n" +
	"\x1bCheckTeamGroupAccessRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\"\x1e\n" +
	"\x1cCheckTeamGroupAccessResponse2\xf2\x05\n" +
	"\x02IM\x12M\n" +
	"\x10CheckGroupMember\x12\x1b.im.CheckGroupMemberRequest\x1a\x1c.im.CheckGroupMemberResponse\x12Y\n" +
	"\x14CheckTeamGroupAccess\x12\x1f.im.CheckTeamGroupAccessRequest\x1a .im.CheckTeamGroupAccessResponse\x12J\n" +
	"\x0fCreateTeamGroup\x12\x1a.im.CreateTeamGroupRequest\x1a\x1b.im.CreateTeamGroupResponse\x12G\n" +
	"\x0eListTeamGroups\x12\x19.im.ListTeamGroupsRequest\x1a\x1a.im.ListTeamGroupsResponse\x12D\n" +
	"\rJoinTeamGroup\x12\x18.im.JoinTeamGroupRequest\x1a\x19.im.JoinTeamGroupResponse\x12\\\n" +
	"\x15ListTeamGroupMessages\x12 .im.ListTeamGroupMessagesRequest\x1a!.im.ListTeamGroupMessagesResponse\x12\\\n" +
	"\x15CheckTeamGroupMessage\x12 .im.CheckTeamGroupMessageRequest\x1a!.im.CheckTeamGroupMessageResponse\x12V\n" +
	"\x13ListOfflineMessages\x12\x1e.im.ListOfflineMessagesRequest\x1a\x1f.im.ListOfflineMessagesResponse\x12S\n" +
	"\x12AckOfflineMessages\x12\x1d.im.AckOfflineMessagesRequest\x1a\x1e.im.AckOfflineMessagesResponseB$Z\"github.com/yjydist/go-im/rpc/im/pbb\x06proto3"

var (
	file_rpc_im_im_proto_rawDescOnce sync.Once
	file_rpc_im_im_proto_rawDescData []byte
)

func file_rpc_im_im_proto_rawDescGZIP() []byte {
	file_rpc_im_im_proto_rawDescOnce.Do(func() {
		file_rpc_im_im_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_im_im_proto_rawDesc), len(file_rpc_im_im_proto_rawDesc)))
	})
	return file_rpc_im_im_proto_rawDescData
}

var file_rpc_im_im_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_rpc_im_im_proto_goTypes = []any{
	(*AckOfflineMessagesRequest)(nil),     // 0: im.AckOfflineMessagesRequest
	(*AckOfflineMessagesResponse)(nil),    // 1: im.AckOfflineMessagesResponse
	(*ListOfflineMessagesRequest)(nil),    // 2: im.ListOfflineMessagesRequest
	(*OfflineMessage)(nil),                // 3: im.OfflineMessage
	(*ListOfflineMessagesResponse)(nil),   // 4: im.ListOfflineMessagesResponse
	(*ListTeamGroupMessagesRequest)(nil),  // 5: im.ListTeamGroupMessagesRequest
	(*TeamGroupMessage)(nil),              // 6: im.TeamGroupMessage
	(*ListTeamGroupMessagesResponse)(nil), // 7: im.ListTeamGroupMessagesResponse
	(*CheckTeamGroupMessageRequest)(nil),  // 8: im.CheckTeamGroupMessageRequest
	(*CheckTeamGroupMessageResponse)(nil), // 9: im.CheckTeamGroupMessageResponse
	(*JoinTeamGroupRequest)(nil),          // 10: im.JoinTeamGroupRequest
	(*JoinTeamGroupResponse)(nil),         // 11: im.JoinTeamGroupResponse
	(*ListTeamGroupsRequest)(nil),         // 12: im.ListTeamGroupsRequest
	(*TeamGroup)(nil),                     // 13: im.TeamGroup
	(*ListTeamGroupsResponse)(nil),        // 14: im.ListTeamGroupsResponse
	(*CreateTeamGroupRequest)(nil),        // 15: im.CreateTeamGroupRequest
	(*CreateTeamGroupResponse)(nil),       // 16: im.CreateTeamGroupResponse
	(*CheckGroupMemberRequest)(nil),       // 17: im.CheckGroupMemberRequest
	(*CheckGroupMemberResponse)(nil),      // 18: im.CheckGroupMemberResponse
	(*CheckTeamGroupAccessRequest)(nil),   // 19: im.CheckTeamGroupAccessRequest
	(*CheckTeamGroupAccessResponse)(nil),  // 20: im.CheckTeamGroupAccessResponse
	(*timestamppb.Timestamp)(nil),         // 21: google.protobuf.Timestamp
}
var file_rpc_im_im_proto_depIdxs = []int32{
	21, // 0: im.OfflineMessage.created_at:type_name -> google.protobuf.Timestamp
	3,  // 1: im.ListOfflineMessagesResponse.messages:type_name -> im.OfflineMessage
	6,  // 2: im.ListTeamGroupMessagesResponse.messages:type_name -> im.TeamGroupMessage
	13, // 3: im.ListTeamGroupsResponse.groups:type_name -> im.TeamGroup
	17, // 4: im.IM.CheckGroupMember:input_type -> im.CheckGroupMemberRequest
	19, // 5: im.IM.CheckTeamGroupAccess:input_type -> im.CheckTeamGroupAccessRequest
	15, // 6: im.IM.CreateTeamGroup:input_type -> im.CreateTeamGroupRequest
	12, // 7: im.IM.ListTeamGroups:input_type -> im.ListTeamGroupsRequest
	10, // 8: im.IM.JoinTeamGroup:input_type -> im.JoinTeamGroupRequest
	5,  // 9: im.IM.ListTeamGroupMessages:input_type -> im.ListTeamGroupMessagesRequest
	8,  // 10: im.IM.CheckTeamGroupMessage:input_type -> im.CheckTeamGroupMessageRequest
	2,  // 11: im.IM.ListOfflineMessages:input_type -> im.ListOfflineMessagesRequest
	0,  // 12: im.IM.AckOfflineMessages:input_type -> im.AckOfflineMessagesRequest
	18, // 13: im.IM.CheckGroupMember:output_type -> im.CheckGroupMemberResponse
	20, // 14: im.IM.CheckTeamGroupAccess:output_type -> im.CheckTeamGroupAccessResponse
	16, // 15: im.IM.CreateTeamGroup:output_type -> im.CreateTeamGroupResponse
	14, // 16: im.IM.ListTeamGroups:output_type -> im.ListTeamGroupsResponse
	11, // 17: im.IM.JoinTeamGroup:output_type -> im.JoinTeamGroupResponse
	7,  // 18: im.IM.ListTeamGroupMessages:output_type -> im.ListTeamGroupMessagesResponse
	9,  // 19: im.IM.CheckTeamGroupMessage:output_type -> im.CheckTeamGroupMessageResponse
	4,  // 20: im.IM.ListOfflineMessages:output_type -> im.ListOfflineMessagesResponse
	1,  // 21: im.IM.AckOfflineMessages:output_type -> im.AckOfflineMessagesResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_im_im_proto_init() }
func file_rpc_im_im_proto_init() {
	if File_rpc_im_im_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_im_im_proto_rawDesc), len(file_rpc_im_im_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_im_im_proto_goTypes,
		DependencyIndexes: file_rpc_im_im_proto_depIdxs,
		MessageInfos:      file_rpc_im_im_proto_msgTypes,
	}.Build()
	File_rpc_im_im_proto = out.File
	file_rpc_im_im_proto_goTypes = nil
	file_rpc_im_im_proto_depIdxs = nil
}
