// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: rpc/im/im.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckOfflineMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageIds    []int64                `protobuf:"varint,1,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckOfflineMessagesRequest) Reset() {
	*x = AckOfflineMessagesRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckOfflineMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckOfflineMessagesRequest) ProtoMessage() {}

func (x *AckOfflineMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckOfflineMessagesRequest.ProtoReflect.Descriptor instead.
func (*AckOfflineMessagesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{0}
}

func (x *AckOfflineMessagesRequest) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type AckOfflineMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckOfflineMessagesResponse) Reset() {
	*x = AckOfflineMessagesResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckOfflineMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckOfflineMessagesResponse) ProtoMessage() {}

func (x *AckOfflineMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckOfflineMessagesResponse.ProtoReflect.Descriptor instead.
func (*AckOfflineMessagesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{1}
}

type ListOfflineMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOfflineMessagesRequest) Reset() {
	*x = ListOfflineMessagesRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOfflineMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfflineMessagesRequest) ProtoMessage() {}

func (x *ListOfflineMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfflineMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListOfflineMessagesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{2}
}

type OfflineMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgId       string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	FromId      int64                  `protobuf:"varint,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId        int64                  `protobuf:"varint,4,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ChatType    int32                  `protobuf:"varint,5,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`
	ContentType int32                  `protobuf:"varint,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content     string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 1: user, 2: IM bot; 0 means a legacy user message.
	SenderType       int32   `protobuf:"varint,9,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	InitiatorId      int64   `protobuf:"varint,10,opt,name=initiator_id,json=initiatorId,proto3" json:"initiator_id,omitempty"`
	MentionedUserIds []int64 `protobuf:"varint,11,rep,packed,name=mentioned_user_ids,json=mentionedUserIds,proto3" json:"mentioned_user_ids,omitempty"` // 仅经核验的新群消息。
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OfflineMessage) Reset() {
	*x = OfflineMessage{}
	mi := &file_rpc_im_im_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineMessage) ProtoMessage() {}

func (x *OfflineMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineMessage.ProtoReflect.Descriptor instead.
func (*OfflineMessage) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{3}
}

func (x *OfflineMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OfflineMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *OfflineMessage) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *OfflineMessage) GetToId() int64 {
	if x != nil {
		return x.ToId
	}
	return 0
}

func (x *OfflineMessage) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *OfflineMessage) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *OfflineMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *OfflineMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OfflineMessage) GetSenderType() int32 {
	if x != nil {
		return x.SenderType
	}
	return 0
}

func (x *OfflineMessage) GetInitiatorId() int64 {
	if x != nil {
		return x.InitiatorId
	}
	return 0
}

func (x *OfflineMessage) GetMentionedUserIds() []int64 {
	if x != nil {
		return x.MentionedUserIds
	}
	return nil
}

type ListOfflineMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*OfflineMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOfflineMessagesResponse) Reset() {
	*x = ListOfflineMessagesResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOfflineMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfflineMessagesResponse) ProtoMessage() {}

func (x *ListOfflineMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfflineMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListOfflineMessagesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{4}
}

func (x *ListOfflineMessagesResponse) GetMessages() []*OfflineMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ListTeamGroupMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TeamId          int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId         int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	BeforeMessageId int64                  `protobuf:"varint,3,opt,name=before_message_id,json=beforeMessageId,proto3" json:"before_message_id,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListTeamGroupMessagesRequest) Reset() {
	*x = ListTeamGroupMessagesRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamGroupMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamGroupMessagesRequest) ProtoMessage() {}

func (x *ListTeamGroupMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamGroupMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListTeamGroupMessagesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{5}
}

func (x *ListTeamGroupMessagesRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ListTeamGroupMessagesRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListTeamGroupMessagesRequest) GetBeforeMessageId() int64 {
	if x != nil {
		return x.BeforeMessageId
	}
	return 0
}

func (x *ListTeamGroupMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TeamGroupMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgId           string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	FromId          int64                  `protobuf:"varint,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ContentType     int32                  `protobuf:"varint,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content         string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,6,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	// from_id refers to a user or bot according to sender_type.
	SenderType       int32   `protobuf:"varint,7,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	InitiatorId      int64   `protobuf:"varint,8,opt,name=initiator_id,json=initiatorId,proto3" json:"initiator_id,omitempty"`
	MentionedUserIds []int64 `protobuf:"varint,9,rep,packed,name=mentioned_user_ids,json=mentionedUserIds,proto3" json:"mentioned_user_ids,omitempty"` // 仅经核验的新消息；旧消息为空。
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TeamGroupMessage) Reset() {
	*x = TeamGroupMessage{}
	mi := &file_rpc_im_im_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamGroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamGroupMessage) ProtoMessage() {}

func (x *TeamGroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamGroupMessage.ProtoReflect.Descriptor instead.
func (*TeamGroupMessage) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{6}
}

func (x *TeamGroupMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TeamGroupMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *TeamGroupMessage) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *TeamGroupMessage) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *TeamGroupMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TeamGroupMessage) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *TeamGroupMessage) GetSenderType() int32 {
	if x != nil {
		return x.SenderType
	}
	return 0
}

func (x *TeamGroupMessage) GetInitiatorId() int64 {
	if x != nil {
		return x.InitiatorId
	}
	return 0
}

func (x *TeamGroupMessage) GetMentionedUserIds() []int64 {
	if x != nil {
		return x.MentionedUserIds
	}
	return nil
}

type ListTeamGroupMessagesResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Messages            []*TeamGroupMessage    `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextBeforeMessageId int64                  `protobuf:"varint,2,opt,name=next_before_message_id,json=nextBeforeMessageId,proto3" json:"next_before_message_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListTeamGroupMessagesResponse) Reset() {
	*x = ListTeamGroupMessagesResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamGroupMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamGroupMessagesResponse) ProtoMessage() {}

func (x *ListTeamGroupMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamGroupMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListTeamGroupMessagesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{7}
}

func (x *ListTeamGroupMessagesResponse) GetMessages() []*TeamGroupMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListTeamGroupMessagesResponse) GetNextBeforeMessageId() int64 {
	if x != nil {
		return x.NextBeforeMessageId
	}
	return 0
}

type CheckTeamGroupMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamGroupMessageRequest) Reset() {
	*x = CheckTeamGroupMessageRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamGroupMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamGroupMessageRequest) ProtoMessage() {}

func (x *CheckTeamGroupMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamGroupMessageRequest.ProtoReflect.Descriptor instead.
func (*CheckTeamGroupMessageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{8}
}

func (x *CheckTeamGroupMessageRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CheckTeamGroupMessageRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CheckTeamGroupMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type CheckTeamGroupMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamGroupMessageResponse) Reset() {
	*x = CheckTeamGroupMessageResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamGroupMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamGroupMessageResponse) ProtoMessage() {}

func (x *CheckTeamGroupMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamGroupMessageResponse.ProtoReflect.Descriptor instead.
func (*CheckTeamGroupMessageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{9}
}

type JoinTeamGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTeamGroupRequest) Reset() {
	*x = JoinTeamGroupRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTeamGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTeamGroupRequest) ProtoMessage() {}

func (x *JoinTeamGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTeamGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinTeamGroupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{10}
}

func (x *JoinTeamGroupRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *JoinTeamGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type JoinTeamGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTeamGroupResponse) Reset() {
	*x = JoinTeamGroupResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTeamGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTeamGroupResponse) ProtoMessage() {}

func (x *JoinTeamGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTeamGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinTeamGroupResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{11}
}

type ListTeamGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	AfterGroupId  int64                  `protobuf:"varint,2,opt,name=after_group_id,json=afterGroupId,proto3" json:"after_group_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamGroupsRequest) Reset() {
	*x = ListTeamGroupsRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamGroupsRequest) ProtoMessage() {}

func (x *ListTeamGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamGroupsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{12}
}

func (x *ListTeamGroupsRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ListTeamGroupsRequest) GetAfterGroupId() int64 {
	if x != nil {
		return x.AfterGroupId
	}
	return 0
}

func (x *ListTeamGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TeamGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Joined        bool                   `protobuf:"varint,4,opt,name=joined,proto3" json:"joined,omitempty"` // 当前团队代际内的群成员资格；看见目录不代表已加入。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamGroup) Reset() {
	*x = TeamGroup{}
	mi := &file_rpc_im_im_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamGroup) ProtoMessage() {}

func (x *TeamGroup) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamGroup.ProtoReflect.Descriptor instead.
func (*TeamGroup) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{13}
}

func (x *TeamGroup) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *TeamGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeamGroup) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *TeamGroup) GetJoined() bool {
	if x != nil {
		return x.Joined
	}
	return false
}

type ListTeamGroupsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Groups           []*TeamGroup           `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	NextAfterGroupId int64                  `protobuf:"varint,2,opt,name=next_after_group_id,json=nextAfterGroupId,proto3" json:"next_after_group_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTeamGroupsResponse) Reset() {
	*x = ListTeamGroupsResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamGroupsResponse) ProtoMessage() {}

func (x *ListTeamGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamGroupsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{14}
}

func (x *ListTeamGroupsResponse) GetGroups() []*TeamGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListTeamGroupsResponse) GetNextAfterGroupId() int64 {
	if x != nil {
		return x.NextAfterGroupId
	}
	return 0
}

type GetTeamGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupRequest) Reset() {
	*x = GetTeamGroupRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupRequest) ProtoMessage() {}

func (x *GetTeamGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupRequest.ProtoReflect.Descriptor instead.
func (*GetTeamGroupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{15}
}

func (x *GetTeamGroupRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GetTeamGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetTeamGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *TeamGroup             `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupResponse) Reset() {
	*x = GetTeamGroupResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupResponse) ProtoMessage() {}

func (x *GetTeamGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupResponse.ProtoReflect.Descriptor instead.
func (*GetTeamGroupResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{16}
}

func (x *GetTeamGroupResponse) GetGroup() *TeamGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type CreateTeamGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamGroupRequest) Reset() {
	*x = CreateTeamGroupRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamGroupRequest) ProtoMessage() {}

func (x *CreateTeamGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamGroupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{17}
}

func (x *CreateTeamGroupRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CreateTeamGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTeamGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamGroupResponse) Reset() {
	*x = CreateTeamGroupResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamGroupResponse) ProtoMessage() {}

func (x *CreateTeamGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamGroupResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{18}
}

func (x *CreateTeamGroupResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type CheckGroupMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckGroupMemberRequest) Reset() {
	*x = CheckGroupMemberRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGroupMemberRequest) ProtoMessage() {}

func (x *CheckGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*CheckGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{19}
}

func (x *CheckGroupMemberRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type CheckGroupMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckGroupMemberResponse) Reset() {
	*x = CheckGroupMemberResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGroupMemberResponse) ProtoMessage() {}

func (x *CheckGroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGroupMemberResponse.ProtoReflect.Descriptor instead.
func (*CheckGroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{20}
}

type CheckTeamGroupAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamGroupAccessRequest) Reset() {
	*x = CheckTeamGroupAccessRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamGroupAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamGroupAccessRequest) ProtoMessage() {}

func (x *CheckTeamGroupAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamGroupAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckTeamGroupAccessRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{21}
}

func (x *CheckTeamGroupAccessRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CheckTeamGroupAccessRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type CheckTeamGroupAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamGroupAccessResponse) Reset() {
	*x = CheckTeamGroupAccessResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamGroupAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamGroupAccessResponse) ProtoMessage() {}

func (x *CheckTeamGroupAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamGroupAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckTeamGroupAccessResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{22}
}

type GetTeamGroupUnreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupUnreadRequest) Reset() {
	*x = GetTeamGroupUnreadRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupUnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupUnreadRequest) ProtoMessage() {}

func (x *GetTeamGroupUnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupUnreadRequest.ProtoReflect.Descriptor instead.
func (*GetTeamGroupUnreadRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{23}
}

func (x *GetTeamGroupUnreadRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GetTeamGroupUnreadRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetTeamGroupUnreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupUnreadResponse) Reset() {
	*x = GetTeamGroupUnreadResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupUnreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupUnreadResponse) ProtoMessage() {}

func (x *GetTeamGroupUnreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupUnreadResponse.ProtoReflect.Descriptor instead.
func (*GetTeamGroupUnreadResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{24}
}

func (x *GetTeamGroupUnreadResponse) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GetTeamGroupUnreadResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetTeamGroupUnreadResponse) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type MarkTeamGroupMessagesReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MessageIds    []int64                `protobuf:"varint,3,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkTeamGroupMessagesReadRequest) Reset() {
	*x = MarkTeamGroupMessagesReadRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkTeamGroupMessagesReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTeamGroupMessagesReadRequest) ProtoMessage() {}

func (x *MarkTeamGroupMessagesReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTeamGroupMessagesReadRequest.ProtoReflect.Descriptor instead.
func (*MarkTeamGroupMessagesReadRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{25}
}

func (x *MarkTeamGroupMessagesReadRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *MarkTeamGroupMessagesReadRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MarkTeamGroupMessagesReadRequest) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type MarkTeamGroupMessagesReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MessageIds    []int64                `protobuf:"varint,3,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,4,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkTeamGroupMessagesReadResponse) Reset() {
	*x = MarkTeamGroupMessagesReadResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkTeamGroupMessagesReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTeamGroupMessagesReadResponse) ProtoMessage() {}

func (x *MarkTeamGroupMessagesReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTeamGroupMessagesReadResponse.ProtoReflect.Descriptor instead.
func (*MarkTeamGroupMessagesReadResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{26}
}

func (x *MarkTeamGroupMessagesReadResponse) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *MarkTeamGroupMessagesReadResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MarkTeamGroupMessagesReadResponse) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

func (x *MarkTeamGroupMessagesReadResponse) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type ListDirectMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          int64                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	BeforeMessageId int64                  `protobuf:"varint,2,opt,name=before_message_id,json=beforeMessageId,proto3" json:"before_message_id,omitempty"`
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListDirectMessagesRequest) Reset() {
	*x = ListDirectMessagesRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectMessagesRequest) ProtoMessage() {}

func (x *ListDirectMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListDirectMessagesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{27}
}

func (x *ListDirectMessagesRequest) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *ListDirectMessagesRequest) GetBeforeMessageId() int64 {
	if x != nil {
		return x.BeforeMessageId
	}
	return 0
}

func (x *ListDirectMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DirectMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgId           string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	FromId          int64                  `protobuf:"varint,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId            int64                  `protobuf:"varint,4,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ContentType     int32                  `protobuf:"varint,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content         string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,7,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DirectMessage) Reset() {
	*x = DirectMessage{}
	mi := &file_rpc_im_im_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectMessage) ProtoMessage() {}

func (x *DirectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectMessage.ProtoReflect.Descriptor instead.
func (*DirectMessage) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{28}
}

func (x *DirectMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DirectMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *DirectMessage) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *DirectMessage) GetToId() int64 {
	if x != nil {
		return x.ToId
	}
	return 0
}

func (x *DirectMessage) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *DirectMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DirectMessage) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type ListMyUnreadConversationsRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SnapshotUpperMessageId int64                  `protobuf:"varint,1,opt,name=snapshot_upper_message_id,json=snapshotUpperMessageId,proto3" json:"snapshot_upper_message_id,omitempty"` // 首次为 0；后续原样回传。
	BeforeLastMessageId    int64                  `protobuf:"varint,2,opt,name=before_last_message_id,json=beforeLastMessageId,proto3" json:"before_last_message_id,omitempty"`          // 首次为 0；后续使用上一页游标。
	Limit                  int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                                                     // 默认 20，最大 50。
	MentionsOnly           bool                   `protobuf:"varint,4,opt,name=mentions_only,json=mentionsOnly,proto3" json:"mentions_only,omitempty"`                                   // 仅返回有未读结构化提及的群会话。
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListMyUnreadConversationsRequest) Reset() {
	*x = ListMyUnreadConversationsRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyUnreadConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyUnreadConversationsRequest) ProtoMessage() {}

func (x *ListMyUnreadConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyUnreadConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListMyUnreadConversationsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{29}
}

func (x *ListMyUnreadConversationsRequest) GetSnapshotUpperMessageId() int64 {
	if x != nil {
		return x.SnapshotUpperMessageId
	}
	return 0
}

func (x *ListMyUnreadConversationsRequest) GetBeforeLastMessageId() int64 {
	if x != nil {
		return x.BeforeLastMessageId
	}
	return 0
}

func (x *ListMyUnreadConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMyUnreadConversationsRequest) GetMentionsOnly() bool {
	if x != nil {
		return x.MentionsOnly
	}
	return false
}

type UnreadConversation struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ChatType              int32                  `protobuf:"varint,1,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`   // 1: 私聊，2: 团队群。
	TeamId                int64                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`         // 仅团队群。
	GroupId               int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`      // 仅团队群。
	PeerId                int64                  `protobuf:"varint,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`         // 仅私聊。
	GroupName             string                 `protobuf:"bytes,5,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"` // IM 内部群名；私聊显示名由 Gateway 补充。
	LastMessageId         int64                  `protobuf:"varint,6,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	LastMessageTimeUnixMs int64                  `protobuf:"varint,7,opt,name=last_message_time_unix_ms,json=lastMessageTimeUnixMs,proto3" json:"last_message_time_unix_ms,omitempty"`
	Preview               string                 `protobuf:"bytes,8,opt,name=preview,proto3" json:"preview,omitempty"` // 最新持久消息的有限纯文本预览。
	UnreadCount           int64                  `protobuf:"varint,9,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	MentionUnreadCount    int64                  `protobuf:"varint,10,opt,name=mention_unread_count,json=mentionUnreadCount,proto3" json:"mention_unread_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UnreadConversation) Reset() {
	*x = UnreadConversation{}
	mi := &file_rpc_im_im_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadConversation) ProtoMessage() {}

func (x *UnreadConversation) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadConversation.ProtoReflect.Descriptor instead.
func (*UnreadConversation) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{30}
}

func (x *UnreadConversation) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *UnreadConversation) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *UnreadConversation) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UnreadConversation) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *UnreadConversation) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UnreadConversation) GetLastMessageId() int64 {
	if x != nil {
		return x.LastMessageId
	}
	return 0
}

func (x *UnreadConversation) GetLastMessageTimeUnixMs() int64 {
	if x != nil {
		return x.LastMessageTimeUnixMs
	}
	return 0
}

func (x *UnreadConversation) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *UnreadConversation) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *UnreadConversation) GetMentionUnreadCount() int64 {
	if x != nil {
		return x.MentionUnreadCount
	}
	return 0
}

type ListMyUnreadConversationsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Conversations           []*UnreadConversation  `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	SnapshotUpperMessageId  int64                  `protobuf:"varint,2,opt,name=snapshot_upper_message_id,json=snapshotUpperMessageId,proto3" json:"snapshot_upper_message_id,omitempty"`
	NextBeforeLastMessageId int64                  `protobuf:"varint,3,opt,name=next_before_last_message_id,json=nextBeforeLastMessageId,proto3" json:"next_before_last_message_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListMyUnreadConversationsResponse) Reset() {
	*x = ListMyUnreadConversationsResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyUnreadConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyUnreadConversationsResponse) ProtoMessage() {}

func (x *ListMyUnreadConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyUnreadConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListMyUnreadConversationsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{31}
}

func (x *ListMyUnreadConversationsResponse) GetConversations() []*UnreadConversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListMyUnreadConversationsResponse) GetSnapshotUpperMessageId() int64 {
	if x != nil {
		return x.SnapshotUpperMessageId
	}
	return 0
}

func (x *ListMyUnreadConversationsResponse) GetNextBeforeLastMessageId() int64 {
	if x != nil {
		return x.NextBeforeLastMessageId
	}
	return 0
}

type ListDirectMessagesResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Messages            []*DirectMessage       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextBeforeMessageId int64                  `protobuf:"varint,2,opt,name=next_before_message_id,json=nextBeforeMessageId,proto3" json:"next_before_message_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListDirectMessagesResponse) Reset() {
	*x = ListDirectMessagesResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectMessagesResponse) ProtoMessage() {}

func (x *ListDirectMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListDirectMessagesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{32}
}

func (x *ListDirectMessagesResponse) GetMessages() []*DirectMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListDirectMessagesResponse) GetNextBeforeMessageId() int64 {
	if x != nil {
		return x.NextBeforeMessageId
	}
	return 0
}

type ListMyDirectConversationsRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SnapshotUpperMessageId int64                  `protobuf:"varint,1,opt,name=snapshot_upper_message_id,json=snapshotUpperMessageId,proto3" json:"snapshot_upper_message_id,omitempty"` // 首页面传 0，后续原样回传。
	BeforeLastMessageId    int64                  `protobuf:"varint,2,opt,name=before_last_message_id,json=beforeLastMessageId,proto3" json:"before_last_message_id,omitempty"`          // 首页面传 0，后续传上一页游标。
	Limit                  int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListMyDirectConversationsRequest) Reset() {
	*x = ListMyDirectConversationsRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyDirectConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyDirectConversationsRequest) ProtoMessage() {}

func (x *ListMyDirectConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyDirectConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListMyDirectConversationsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{33}
}

func (x *ListMyDirectConversationsRequest) GetSnapshotUpperMessageId() int64 {
	if x != nil {
		return x.SnapshotUpperMessageId
	}
	return 0
}

func (x *ListMyDirectConversationsRequest) GetBeforeLastMessageId() int64 {
	if x != nil {
		return x.BeforeLastMessageId
	}
	return 0
}

func (x *ListMyDirectConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DirectConversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int64                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	LastMessageId int64                  `protobuf:"varint,2,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"` // 快照上界以内该会话最新持久消息。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectConversation) Reset() {
	*x = DirectConversation{}
	mi := &file_rpc_im_im_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectConversation) ProtoMessage() {}

func (x *DirectConversation) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectConversation.ProtoReflect.Descriptor instead.
func (*DirectConversation) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{34}
}

func (x *DirectConversation) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *DirectConversation) GetLastMessageId() int64 {
	if x != nil {
		return x.LastMessageId
	}
	return 0
}

type ListMyDirectConversationsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Conversations           []*DirectConversation  `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	SnapshotUpperMessageId  int64                  `protobuf:"varint,2,opt,name=snapshot_upper_message_id,json=snapshotUpperMessageId,proto3" json:"snapshot_upper_message_id,omitempty"`
	NextBeforeLastMessageId int64                  `protobuf:"varint,3,opt,name=next_before_last_message_id,json=nextBeforeLastMessageId,proto3" json:"next_before_last_message_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListMyDirectConversationsResponse) Reset() {
	*x = ListMyDirectConversationsResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyDirectConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyDirectConversationsResponse) ProtoMessage() {}

func (x *ListMyDirectConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyDirectConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListMyDirectConversationsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{35}
}

func (x *ListMyDirectConversationsResponse) GetConversations() []*DirectConversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListMyDirectConversationsResponse) GetSnapshotUpperMessageId() int64 {
	if x != nil {
		return x.SnapshotUpperMessageId
	}
	return 0
}

func (x *ListMyDirectConversationsResponse) GetNextBeforeLastMessageId() int64 {
	if x != nil {
		return x.NextBeforeLastMessageId
	}
	return 0
}

type GetMyDirectConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int64                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyDirectConversationRequest) Reset() {
	*x = GetMyDirectConversationRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyDirectConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyDirectConversationRequest) ProtoMessage() {}

func (x *GetMyDirectConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyDirectConversationRequest.ProtoReflect.Descriptor instead.
func (*GetMyDirectConversationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{36}
}

func (x *GetMyDirectConversationRequest) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

type GetMyDirectConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *DirectConversation    `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyDirectConversationResponse) Reset() {
	*x = GetMyDirectConversationResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyDirectConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyDirectConversationResponse) ProtoMessage() {}

func (x *GetMyDirectConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyDirectConversationResponse.ProtoReflect.Descriptor instead.
func (*GetMyDirectConversationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{37}
}

func (x *GetMyDirectConversationResponse) GetConversation() *DirectConversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

type GetDirectUnreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int64                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectUnreadRequest) Reset() {
	*x = GetDirectUnreadRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectUnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectUnreadRequest) ProtoMessage() {}

func (x *GetDirectUnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectUnreadRequest.ProtoReflect.Descriptor instead.
func (*GetDirectUnreadRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{38}
}

func (x *GetDirectUnreadRequest) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

type GetDirectUnreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int64                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,2,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectUnreadResponse) Reset() {
	*x = GetDirectUnreadResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectUnreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectUnreadResponse) ProtoMessage() {}

func (x *GetDirectUnreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectUnreadResponse.ProtoReflect.Descriptor instead.
func (*GetDirectUnreadResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{39}
}

func (x *GetDirectUnreadResponse) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *GetDirectUnreadResponse) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type MarkDirectMessagesReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int64                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	MessageIds    []int64                `protobuf:"varint,2,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkDirectMessagesReadRequest) Reset() {
	*x = MarkDirectMessagesReadRequest{}
	mi := &file_rpc_im_im_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkDirectMessagesReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkDirectMessagesReadRequest) ProtoMessage() {}

func (x *MarkDirectMessagesReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkDirectMessagesReadRequest.ProtoReflect.Descriptor instead.
func (*MarkDirectMessagesReadRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{40}
}

func (x *MarkDirectMessagesReadRequest) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *MarkDirectMessagesReadRequest) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type MarkDirectMessagesReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int64                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	MessageIds    []int64                `protobuf:"varint,2,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkDirectMessagesReadResponse) Reset() {
	*x = MarkDirectMessagesReadResponse{}
	mi := &file_rpc_im_im_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkDirectMessagesReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkDirectMessagesReadResponse) ProtoMessage() {}

func (x *MarkDirectMessagesReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_im_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkDirectMessagesReadResponse.ProtoReflect.Descriptor instead.
func (*MarkDirectMessagesReadResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_im_proto_rawDescGZIP(), []int{41}
}

func (x *MarkDirectMessagesReadResponse) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *MarkDirectMessagesReadResponse) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

func (x *MarkDirectMessagesReadResponse) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

var File_rpc_im_im_proto protoreflect.FileDescriptor

const file_rpc_im_im_proto_rawDesc = "" +
	"\n" +
	"\x0frpc/im/im.proto\x12\x02im\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\x19AckOfflineMessagesRequest\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\x03R\n" +
	"messageIds\"\x1c\n" +
	"\x1aAckOfflineMessagesResponse\"\x1c\n" +
	"\x1aListOfflineMessagesRequest\"\xec\x02\n" +
	"\x0eOfflineMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x17\n" +
	"\afrom_id\x18\x03 \x01(\x03R\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x04 \x01(\x03R\x04toId\x12\x1b\n" +
	"\tchat_type\x18\x05 \x01(\x05R\bchatType\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\x05R\vcontentType\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vsender_type\x18\t \x01(\x05R\n" +
	"senderType\x12!\n" +
	"\finitiator_id\x18\n" +
	" \x01(\x03R\vinitiatorId\x12,\n" +
	"\x12mentioned_user_ids\x18\v \x03(\x03R\x10mentionedUserIds\"M\n" +
	"\x1bListOfflineMessagesResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.im.OfflineMessageR\bmessages\"\x94\x01\n" +
	"\x1cListTeamGroupMessagesRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12*\n" +
	"\x11before_message_id\x18\x03 \x01(\x03R\x0fbeforeMessageId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xae\x02\n" +
	"\x10TeamGroupMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x17\n" +
	"\afrom_id\x18\x03 \x01(\x03R\x06fromId\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\x05R\vcontentType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12+\n" +
	"\x12created_at_unix_ms\x18\x06 \x01(\x03R\x0fcreatedAtUnixMs\x12\x1f\n" +
	"\vsender_type\x18\a \x01(\x05R\n" +
	"senderType\x12!\n" +
	"\finitiator_id\x18\b \x01(\x03R\vinitiatorId\x12,\n" +
	"\x12mentioned_user_ids\x18\t \x03(\x03R\x10mentionedUserIds\"\x86\x01\n" +
	"\x1dListTeamGroupMessagesResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.im.TeamGroupMessageR\bmessages\x123\n" +
	"\x16next_before_message_id\x18\x02 \x01(\x03R\x13nextBeforeMessageId\"q\n" +
	"\x1cCheckTeamGroupMessageRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\"\x1f\n" +
	"\x1dCheckTeamGroupMessageResponse\"J\n" +
	"\x14JoinTeamGroupRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\"\x17\n" +
	"\x15JoinTeamGroupResponse\"l\n" +
	"\x15ListTeamGroupsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12$\n" +
	"\x0eafter_group_id\x18\x02 \x01(\x03R\fafterGroupId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"m\n" +
	"\tTeamGroup\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12\x16\n" +
	"\x06joined\x18\x04 \x01(\bR\x06joined\"n\n" +
	"\x16ListTeamGroupsResponse\x12%\n" +
	"\x06groups\x18\x01 \x03(\v2\r.im.TeamGroupR\x06groups\x12-\n" +
	"\x13next_after_group_id\x18\x02 \x01(\x03R\x10nextAfterGroupId\"I\n" +
	"\x13GetTeamGroupRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\";\n" +
	"\x14GetTeamGroupResponse\x12#\n" +
	"\x05group\x18\x01 \x01(\v2\r.im.TeamGroupR\x05group\"E\n" +
	"\x16CreateTeamGroupRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"4\n" +
	"\x17CreateTeamGroupResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"4\n" +
	"\x17CheckGroupMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"\x1a\n" +
	"\x18CheckGroupMemberResponse\"Q\n" +
	"\x1bCheckTeamGroupAccessRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\"\x1e\n" +
	"\x1cCheckTeamGroupAccessResponse\"O\n" +
	"\x19GetTeamGroupUnreadRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\"s\n" +
	"\x1aGetTeamGroupUnreadResponse\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12!\n" +
	"\funread_count\x18\x03 \x01(\x03R\vunreadCount\"w\n" +
	" MarkTeamGroupMessagesReadRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x1f\n" +
	"\vmessage_ids\x18\x03 \x03(\x03R\n" +
	"messageIds\"\x9b\x01\n" +
	"!MarkTeamGroupMessagesReadResponse\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x1f\n" +
	"\vmessage_ids\x18\x03 \x03(\x03R\n" +
	"messageIds\x12!\n" +
	"\funread_count\x18\x04 \x01(\x03R\vunreadCount\"v\n" +
	"\x19ListDirectMessagesRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x03R\x06peerId\x12*\n" +
	"\x11before_message_id\x18\x02 \x01(\x03R\x0fbeforeMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xce\x01\n" +
	"\rDirectMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x17\n" +
	"\afrom_id\x18\x03 \x01(\x03R\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x04 \x01(\x03R\x04toId\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\x05R\vcontentType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12+\n" +
	"\x12created_at_unix_ms\x18\a \x01(\x03R\x0fcreatedAtUnixMs\"\xcd\x01\n" +
	" ListMyUnreadConversationsRequest\x129\n" +
	"\x19snapshot_upper_message_id\x18\x01 \x01(\x03R\x16snapshotUpperMessageId\x123\n" +
	"\x16before_last_message_id\x18\x02 \x01(\x03R\x13beforeLastMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12#\n" +
	"\rmentions_only\x18\x04 \x01(\bR\fmentionsOnly\"\xee\x02\n" +
	"\x12UnreadConversation\x12\x1b\n" +
	"\tchat_type\x18\x01 \x01(\x05R\bchatType\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\x03R\x06peerId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x05 \x01(\tR\tgroupName\x12&\n" +
	"\x0flast_message_id\x18\x06 \x01(\x03R\rlastMessageId\x128\n" +
	"\x19last_message_time_unix_ms\x18\a \x01(\x03R\x15lastMessageTimeUnixMs\x12\x18\n" +
	"\apreview\x18\b \x01(\tR\apreview\x12!\n" +
	"\funread_count\x18\t \x01(\x03R\vunreadCount\x120\n" +
	"\x14mention_unread_count\x18\n" +
	" \x01(\x03R\x12mentionUnreadCount\"\xda\x01\n" +
	"!ListMyUnreadConversationsResponse\x12<\n" +
	"\rconversations\x18\x01 \x03(\v2\x16.im.UnreadConversationR\rconversations\x129\n" +
	"\x19snapshot_upper_message_id\x18\x02 \x01(\x03R\x16snapshotUpperMessageId\x12<\n" +
	"\x1bnext_before_last_message_id\x18\x03 \x01(\x03R\x17nextBeforeLastMessageId\"\x80\x01\n" +
	"\x1aListDirectMessagesResponse\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.im.DirectMessageR\bmessages\x123\n" +
	"\x16next_before_message_id\x18\x02 \x01(\x03R\x13nextBeforeMessageId\"\xa8\x01\n" +
	" ListMyDirectConversationsRequest\x129\n" +
	"\x19snapshot_upper_message_id\x18\x01 \x01(\x03R\x16snapshotUpperMessageId\x123\n" +
	"\x16before_last_message_id\x18\x02 \x01(\x03R\x13beforeLastMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"U\n" +
	"\x12DirectConversation\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x03R\x06peerId\x12&\n" +
	"\x0flast_message_id\x18\x02 \x01(\x03R\rlastMessageId\"\xda\x01\n" +
	"!ListMyDirectConversationsResponse\x12<\n" +
	"\rconversations\x18\x01 \x03(\v2\x16.im.DirectConversationR\rconversations\x129\n" +
	"\x19snapshot_upper_message_id\x18\x02 \x01(\x03R\x16snapshotUpperMessageId\x12<\n" +
	"\x1bnext_before_last_message_id\x18\x03 \x01(\x03R\x17nextBeforeLastMessageId\"9\n" +
	"\x1eGetMyDirectConversationRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x03R\x06peerId\"]\n" +
	"\x1fGetMyDirectConversationResponse\x12:\n" +
	"\fconversation\x18\x01 \x01(\v2\x16.im.DirectConversationR\fconversation\"1\n" +
	"\x16GetDirectUnreadRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x03R\x06peerId\"U\n" +
	"\x17GetDirectUnreadResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x03R\x06peerId\x12!\n" +
	"\funread_count\x18\x02 \x01(\x03R\vunreadCount\"Y\n" +
	"\x1dMarkDirectMessagesReadRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x03R\x06peerId\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\x03R\n" +
	"messageIds\"}\n" +
	"\x1eMarkDirectMessagesReadResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x03R\x06peerId\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\x03R\n" +
	"messageIds\x12!\n" +
	"\funread_count\x18\x03 \x01(\x03R\vunreadCount2\xae\f\n" +
	"\x02IM\x12M\n" +
	"\x10CheckGroupMember\x12\x1b.im.CheckGroupMemberRequest\x1a\x1c.im.CheckGroupMemberResponse\x12Y\n" +
	"\x14CheckTeamGroupAccess\x12\x1f.im.CheckTeamGroupAccessRequest\x1a .im.CheckTeamGroupAccessResponse\x12J\n" +
	"\x0fCreateTeamGroup\x12\x1a.im.CreateTeamGroupRequest\x1a\x1b.im.CreateTeamGroupResponse\x12G\n" +
	"\x0eListTeamGroups\x12\x19.im.ListTeamGroupsRequest\x1a\x1a.im.ListTeamGroupsResponse\x12A\n" +
	"\fGetTeamGroup\x12\x17.im.GetTeamGroupRequest\x1a\x18.im.GetTeamGroupResponse\x12D\n" +
	"\rJoinTeamGroup\x12\x18.im.JoinTeamGroupRequest\x1a\x19.im.JoinTeamGroupResponse\x12\\\n" +
	"\x15ListTeamGroupMessages\x12 .im.ListTeamGroupMessagesRequest\x1a!.im.ListTeamGroupMessagesResponse\x12S\n" +
	"\x12GetTeamGroupUnread\x12\x1d.im.GetTeamGroupUnreadRequest\x1a\x1e.im.GetTeamGroupUnreadResponse\x12h\n" +
	"\x19MarkTeamGroupMessagesRead\x12$.im.MarkTeamGroupMessagesReadRequest\x1a%.im.MarkTeamGroupMessagesReadResponse\x12S\n" +
	"\x12ListDirectMessages\x12\x1d.im.ListDirectMessagesRequest\x1a\x1e.im.ListDirectMessagesResponse\x12h\n" +
	"\x19ListMyDirectConversations\x12$.im.ListMyDirectConversationsRequest\x1a%.im.ListMyDirectConversationsResponse\x12b\n" +
	"\x17GetMyDirectConversation\x12\".im.GetMyDirectConversationRequest\x1a#.im.GetMyDirectConversationResponse\x12J\n" +
	"\x0fGetDirectUnread\x12\x1a.im.GetDirectUnreadRequest\x1a\x1b.im.GetDirectUnreadResponse\x12_\n" +
	"\x16MarkDirectMessagesRead\x12!.im.MarkDirectMessagesReadRequest\x1a\".im.MarkDirectMessagesReadResponse\x12h\n" +
	"\x19ListMyUnreadConversations\x12$.im.ListMyUnreadConversationsRequest\x1a%.im.ListMyUnreadConversationsResponse\x12\\\n" +
	"\x15CheckTeamGroupMessage\x12 .im.CheckTeamGroupMessageRequest\x1a!.im.CheckTeamGroupMessageResponse\x12V\n" +
	"\x13ListOfflineMessages\x12\x1e.im.ListOfflineMessagesRequest\x1a\x1f.im.ListOfflineMessagesResponse\x12S\n" +
	"\x12AckOfflineMessages\x12\x1d.im.AckOfflineMessagesRequest\x1a\x1e.im.AckOfflineMessagesResponseB$Z\"github.com/yjydist/go-im/rpc/im/pbb\x06proto3"

var (
	file_rpc_im_im_proto_rawDescOnce sync.Once
	file_rpc_im_im_proto_rawDescData []byte
)

func file_rpc_im_im_proto_rawDescGZIP() []byte {
	file_rpc_im_im_proto_rawDescOnce.Do(func() {
		file_rpc_im_im_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_im_im_proto_rawDesc), len(file_rpc_im_im_proto_rawDesc)))
	})
	return file_rpc_im_im_proto_rawDescData
}

var file_rpc_im_im_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_rpc_im_im_proto_goTypes = []any{
	(*AckOfflineMessagesRequest)(nil),         // 0: im.AckOfflineMessagesRequest
	(*AckOfflineMessagesResponse)(nil),        // 1: im.AckOfflineMessagesResponse
	(*ListOfflineMessagesRequest)(nil),        // 2: im.ListOfflineMessagesRequest
	(*OfflineMessage)(nil),                    // 3: im.OfflineMessage
	(*ListOfflineMessagesResponse)(nil),       // 4: im.ListOfflineMessagesResponse
	(*ListTeamGroupMessagesRequest)(nil),      // 5: im.ListTeamGroupMessagesRequest
	(*TeamGroupMessage)(nil),                  // 6: im.TeamGroupMessage
	(*ListTeamGroupMessagesResponse)(nil),     // 7: im.ListTeamGroupMessagesResponse
	(*CheckTeamGroupMessageRequest)(nil),      // 8: im.CheckTeamGroupMessageRequest
	(*CheckTeamGroupMessageResponse)(nil),     // 9: im.CheckTeamGroupMessageResponse
	(*JoinTeamGroupRequest)(nil),              // 10: im.JoinTeamGroupRequest
	(*JoinTeamGroupResponse)(nil),             // 11: im.JoinTeamGroupResponse
	(*ListTeamGroupsRequest)(nil),             // 12: im.ListTeamGroupsRequest
	(*TeamGroup)(nil),                         // 13: im.TeamGroup
	(*ListTeamGroupsResponse)(nil),            // 14: im.ListTeamGroupsResponse
	(*GetTeamGroupRequest)(nil),               // 15: im.GetTeamGroupRequest
	(*GetTeamGroupResponse)(nil),              // 16: im.GetTeamGroupResponse
	(*CreateTeamGroupRequest)(nil),            // 17: im.CreateTeamGroupRequest
	(*CreateTeamGroupResponse)(nil),           // 18: im.CreateTeamGroupResponse
	(*CheckGroupMemberRequest)(nil),           // 19: im.CheckGroupMemberRequest
	(*CheckGroupMemberResponse)(nil),          // 20: im.CheckGroupMemberResponse
	(*CheckTeamGroupAccessRequest)(nil),       // 21: im.CheckTeamGroupAccessRequest
	(*CheckTeamGroupAccessResponse)(nil),      // 22: im.CheckTeamGroupAccessResponse
	(*GetTeamGroupUnreadRequest)(nil),         // 23: im.GetTeamGroupUnreadRequest
	(*GetTeamGroupUnreadResponse)(nil),        // 24: im.GetTeamGroupUnreadResponse
	(*MarkTeamGroupMessagesReadRequest)(nil),  // 25: im.MarkTeamGroupMessagesReadRequest
	(*MarkTeamGroupMessagesReadResponse)(nil), // 26: im.MarkTeamGroupMessagesReadResponse
	(*ListDirectMessagesRequest)(nil),         // 27: im.ListDirectMessagesRequest
	(*DirectMessage)(nil),                     // 28: im.DirectMessage
	(*ListMyUnreadConversationsRequest)(nil),  // 29: im.ListMyUnreadConversationsRequest
	(*UnreadConversation)(nil),                // 30: im.UnreadConversation
	(*ListMyUnreadConversationsResponse)(nil), // 31: im.ListMyUnreadConversationsResponse
	(*ListDirectMessagesResponse)(nil),        // 32: im.ListDirectMessagesResponse
	(*ListMyDirectConversationsRequest)(nil),  // 33: im.ListMyDirectConversationsRequest
	(*DirectConversation)(nil),                // 34: im.DirectConversation
	(*ListMyDirectConversationsResponse)(nil), // 35: im.ListMyDirectConversationsResponse
	(*GetMyDirectConversationRequest)(nil),    // 36: im.GetMyDirectConversationRequest
	(*GetMyDirectConversationResponse)(nil),   // 37: im.GetMyDirectConversationResponse
	(*GetDirectUnreadRequest)(nil),            // 38: im.GetDirectUnreadRequest
	(*GetDirectUnreadResponse)(nil),           // 39: im.GetDirectUnreadResponse
	(*MarkDirectMessagesReadRequest)(nil),     // 40: im.MarkDirectMessagesReadRequest
	(*MarkDirectMessagesReadResponse)(nil),    // 41: im.MarkDirectMessagesReadResponse
	(*timestamppb.Timestamp)(nil),             // 42: google.protobuf.Timestamp
}
var file_rpc_im_im_proto_depIdxs = []int32{
	42, // 0: im.OfflineMessage.created_at:type_name -> google.protobuf.Timestamp
	3,  // 1: im.ListOfflineMessagesResponse.messages:type_name -> im.OfflineMessage
	6,  // 2: im.ListTeamGroupMessagesResponse.messages:type_name -> im.TeamGroupMessage
	13, // 3: im.ListTeamGroupsResponse.groups:type_name -> im.TeamGroup
	13, // 4: im.GetTeamGroupResponse.group:type_name -> im.TeamGroup
	30, // 5: im.ListMyUnreadConversationsResponse.conversations:type_name -> im.UnreadConversation
	28, // 6: im.ListDirectMessagesResponse.messages:type_name -> im.DirectMessage
	34, // 7: im.ListMyDirectConversationsResponse.conversations:type_name -> im.DirectConversation
	34, // 8: im.GetMyDirectConversationResponse.conversation:type_name -> im.DirectConversation
	19, // 9: im.IM.CheckGroupMember:input_type -> im.CheckGroupMemberRequest
	21, // 10: im.IM.CheckTeamGroupAccess:input_type -> im.CheckTeamGroupAccessRequest
	17, // 11: im.IM.CreateTeamGroup:input_type -> im.CreateTeamGroupRequest
	12, // 12: im.IM.ListTeamGroups:input_type -> im.ListTeamGroupsRequest
	15, // 13: im.IM.GetTeamGroup:input_type -> im.GetTeamGroupRequest
	10, // 14: im.IM.JoinTeamGroup:input_type -> im.JoinTeamGroupRequest
	5,  // 15: im.IM.ListTeamGroupMessages:input_type -> im.ListTeamGroupMessagesRequest
	23, // 16: im.IM.GetTeamGroupUnread:input_type -> im.GetTeamGroupUnreadRequest
	25, // 17: im.IM.MarkTeamGroupMessagesRead:input_type -> im.MarkTeamGroupMessagesReadRequest
	27, // 18: im.IM.ListDirectMessages:input_type -> im.ListDirectMessagesRequest
	33, // 19: im.IM.ListMyDirectConversations:input_type -> im.ListMyDirectConversationsRequest
	36, // 20: im.IM.GetMyDirectConversation:input_type -> im.GetMyDirectConversationRequest
	38, // 21: im.IM.GetDirectUnread:input_type -> im.GetDirectUnreadRequest
	40, // 22: im.IM.MarkDirectMessagesRead:input_type -> im.MarkDirectMessagesReadRequest
	29, // 23: im.IM.ListMyUnreadConversations:input_type -> im.ListMyUnreadConversationsRequest
	8,  // 24: im.IM.CheckTeamGroupMessage:input_type -> im.CheckTeamGroupMessageRequest
	2,  // 25: im.IM.ListOfflineMessages:input_type -> im.ListOfflineMessagesRequest
	0,  // 26: im.IM.AckOfflineMessages:input_type -> im.AckOfflineMessagesRequest
	20, // 27: im.IM.CheckGroupMember:output_type -> im.CheckGroupMemberResponse
	22, // 28: im.IM.CheckTeamGroupAccess:output_type -> im.CheckTeamGroupAccessResponse
	18, // 29: im.IM.CreateTeamGroup:output_type -> im.CreateTeamGroupResponse
	14, // 30: im.IM.ListTeamGroups:output_type -> im.ListTeamGroupsResponse
	16, // 31: im.IM.GetTeamGroup:output_type -> im.GetTeamGroupResponse
	11, // 32: im.IM.JoinTeamGroup:output_type -> im.JoinTeamGroupResponse
	7,  // 33: im.IM.ListTeamGroupMessages:output_type -> im.ListTeamGroupMessagesResponse
	24, // 34: im.IM.GetTeamGroupUnread:output_type -> im.GetTeamGroupUnreadResponse
	26, // 35: im.IM.MarkTeamGroupMessagesRead:output_type -> im.MarkTeamGroupMessagesReadResponse
	32, // 36: im.IM.ListDirectMessages:output_type -> im.ListDirectMessagesResponse
	35, // 37: im.IM.ListMyDirectConversations:output_type -> im.ListMyDirectConversationsResponse
	37, // 38: im.IM.GetMyDirectConversation:output_type -> im.GetMyDirectConversationResponse
	39, // 39: im.IM.GetDirectUnread:output_type -> im.GetDirectUnreadResponse
	41, // 40: im.IM.MarkDirectMessagesRead:output_type -> im.MarkDirectMessagesReadResponse
	31, // 41: im.IM.ListMyUnreadConversations:output_type -> im.ListMyUnreadConversationsResponse
	9,  // 42: im.IM.CheckTeamGroupMessage:output_type -> im.CheckTeamGroupMessageResponse
	4,  // 43: im.IM.ListOfflineMessages:output_type -> im.ListOfflineMessagesResponse
	1,  // 44: im.IM.AckOfflineMessages:output_type -> im.AckOfflineMessagesResponse
	27, // [27:45] is the sub-list for method output_type
	9,  // [9:27] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_rpc_im_im_proto_init() }
func file_rpc_im_im_proto_init() {
	if File_rpc_im_im_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_im_im_proto_rawDesc), len(file_rpc_im_im_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_im_im_proto_goTypes,
		DependencyIndexes: file_rpc_im_im_proto_depIdxs,
		MessageInfos:      file_rpc_im_im_proto_msgTypes,
	}.Build()
	File_rpc_im_im_proto = out.File
	file_rpc_im_im_proto_goTypes = nil
	file_rpc_im_im_proto_depIdxs = nil
}
