// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: rpc/im/im.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IM_CheckGroupMember_FullMethodName          = "/im.IM/CheckGroupMember"
	IM_CheckTeamGroupAccess_FullMethodName      = "/im.IM/CheckTeamGroupAccess"
	IM_CreateTeamGroup_FullMethodName           = "/im.IM/CreateTeamGroup"
	IM_ListTeamGroups_FullMethodName            = "/im.IM/ListTeamGroups"
	IM_JoinTeamGroup_FullMethodName             = "/im.IM/JoinTeamGroup"
	IM_ListTeamGroupMessages_FullMethodName     = "/im.IM/ListTeamGroupMessages"
	IM_GetTeamGroupUnread_FullMethodName        = "/im.IM/GetTeamGroupUnread"
	IM_MarkTeamGroupMessagesRead_FullMethodName = "/im.IM/MarkTeamGroupMessagesRead"
	IM_ListDirectMessages_FullMethodName        = "/im.IM/ListDirectMessages"
	IM_GetDirectUnread_FullMethodName           = "/im.IM/GetDirectUnread"
	IM_MarkDirectMessagesRead_FullMethodName    = "/im.IM/MarkDirectMessagesRead"
	IM_CheckTeamGroupMessage_FullMethodName     = "/im.IM/CheckTeamGroupMessage"
	IM_ListOfflineMessages_FullMethodName       = "/im.IM/ListOfflineMessages"
	IM_AckOfflineMessages_FullMethodName        = "/im.IM/AckOfflineMessages"
)

// IMClient is the client API for IM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IMClient interface {
	// 从 authorization metadata 确定用户，检查其是否属于群及所属团队。
	CheckGroupMember(ctx context.Context, in *CheckGroupMemberRequest, opts ...grpc.CallOption) (*CheckGroupMemberResponse, error)
	// 核对当前用户属于指定团队中的指定群，不读取消息正文。
	CheckTeamGroupAccess(ctx context.Context, in *CheckTeamGroupAccessRequest, opts ...grpc.CallOption) (*CheckTeamGroupAccessResponse, error)
	// 团队拥有者创建团队群，并加入为群主。
	CreateTeamGroup(ctx context.Context, in *CreateTeamGroupRequest, opts ...grpc.CallOption) (*CreateTeamGroupResponse, error)
	// 团队成员分页查看所属团队的群。
	ListTeamGroups(ctx context.Context, in *ListTeamGroupsRequest, opts ...grpc.CallOption) (*ListTeamGroupsResponse, error)
	// 当前团队成员自行加入所属团队的群；用户身份从 authorization 获取。
	JoinTeamGroup(ctx context.Context, in *JoinTeamGroupRequest, opts ...grpc.CallOption) (*JoinTeamGroupResponse, error)
	// 团队群成员按消息 ID 倒序读取历史消息。
	ListTeamGroupMessages(ctx context.Context, in *ListTeamGroupMessagesRequest, opts ...grpc.CallOption) (*ListTeamGroupMessagesResponse, error)
	// 本人当前团队群未读数；读取不标已读。
	GetTeamGroupUnread(ctx context.Context, in *GetTeamGroupUnreadRequest, opts ...grpc.CallOption) (*GetTeamGroupUnreadResponse, error)
	// 明确确认已加载的具体消息；不使用消息ID高水位。
	MarkTeamGroupMessagesRead(ctx context.Context, in *MarkTeamGroupMessagesReadRequest, opts ...grpc.CallOption) (*MarkTeamGroupMessagesReadResponse, error)
	// 本人和指定对方的单聊历史，按消息 ID 倒序分页。
	ListDirectMessages(ctx context.Context, in *ListDirectMessagesRequest, opts ...grpc.CallOption) (*ListDirectMessagesResponse, error)
	// 本人收到该对方消息的未读数；读取不标已读。
	GetDirectUnread(ctx context.Context, in *GetDirectUnreadRequest, opts ...grpc.CallOption) (*GetDirectUnreadResponse, error)
	// 本人显式确认该对方发来的具体消息。
	MarkDirectMessagesRead(ctx context.Context, in *MarkDirectMessagesReadRequest, opts ...grpc.CallOption) (*MarkDirectMessagesReadResponse, error)
	// 核对当前用户可访问指定团队群中的来源消息，供任务服务建立引用。
	CheckTeamGroupMessage(ctx context.Context, in *CheckTeamGroupMessageRequest, opts ...grpc.CallOption) (*CheckTeamGroupMessageResponse, error)
	// 从 authorization metadata 确定本人，只读拉取尚未确认的离线消息。
	ListOfflineMessages(ctx context.Context, in *ListOfflineMessagesRequest, opts ...grpc.CallOption) (*ListOfflineMessagesResponse, error)
	// 当前用户处理完消息后，按消息 ID 确认离线投递。
	AckOfflineMessages(ctx context.Context, in *AckOfflineMessagesRequest, opts ...grpc.CallOption) (*AckOfflineMessagesResponse, error)
}

type iMClient struct {
	cc grpc.ClientConnInterface
}

func NewIMClient(cc grpc.ClientConnInterface) IMClient {
	return &iMClient{cc}
}

func (c *iMClient) CheckGroupMember(ctx context.Context, in *CheckGroupMemberRequest, opts ...grpc.CallOption) (*CheckGroupMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckGroupMemberResponse)
	err := c.cc.Invoke(ctx, IM_CheckGroupMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) CheckTeamGroupAccess(ctx context.Context, in *CheckTeamGroupAccessRequest, opts ...grpc.CallOption) (*CheckTeamGroupAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTeamGroupAccessResponse)
	err := c.cc.Invoke(ctx, IM_CheckTeamGroupAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) CreateTeamGroup(ctx context.Context, in *CreateTeamGroupRequest, opts ...grpc.CallOption) (*CreateTeamGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTeamGroupResponse)
	err := c.cc.Invoke(ctx, IM_CreateTeamGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) ListTeamGroups(ctx context.Context, in *ListTeamGroupsRequest, opts ...grpc.CallOption) (*ListTeamGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTeamGroupsResponse)
	err := c.cc.Invoke(ctx, IM_ListTeamGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) JoinTeamGroup(ctx context.Context, in *JoinTeamGroupRequest, opts ...grpc.CallOption) (*JoinTeamGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinTeamGroupResponse)
	err := c.cc.Invoke(ctx, IM_JoinTeamGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) ListTeamGroupMessages(ctx context.Context, in *ListTeamGroupMessagesRequest, opts ...grpc.CallOption) (*ListTeamGroupMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTeamGroupMessagesResponse)
	err := c.cc.Invoke(ctx, IM_ListTeamGroupMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) GetTeamGroupUnread(ctx context.Context, in *GetTeamGroupUnreadRequest, opts ...grpc.CallOption) (*GetTeamGroupUnreadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamGroupUnreadResponse)
	err := c.cc.Invoke(ctx, IM_GetTeamGroupUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) MarkTeamGroupMessagesRead(ctx context.Context, in *MarkTeamGroupMessagesReadRequest, opts ...grpc.CallOption) (*MarkTeamGroupMessagesReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkTeamGroupMessagesReadResponse)
	err := c.cc.Invoke(ctx, IM_MarkTeamGroupMessagesRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) ListDirectMessages(ctx context.Context, in *ListDirectMessagesRequest, opts ...grpc.CallOption) (*ListDirectMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirectMessagesResponse)
	err := c.cc.Invoke(ctx, IM_ListDirectMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) GetDirectUnread(ctx context.Context, in *GetDirectUnreadRequest, opts ...grpc.CallOption) (*GetDirectUnreadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDirectUnreadResponse)
	err := c.cc.Invoke(ctx, IM_GetDirectUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) MarkDirectMessagesRead(ctx context.Context, in *MarkDirectMessagesReadRequest, opts ...grpc.CallOption) (*MarkDirectMessagesReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkDirectMessagesReadResponse)
	err := c.cc.Invoke(ctx, IM_MarkDirectMessagesRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) CheckTeamGroupMessage(ctx context.Context, in *CheckTeamGroupMessageRequest, opts ...grpc.CallOption) (*CheckTeamGroupMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTeamGroupMessageResponse)
	err := c.cc.Invoke(ctx, IM_CheckTeamGroupMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) ListOfflineMessages(ctx context.Context, in *ListOfflineMessagesRequest, opts ...grpc.CallOption) (*ListOfflineMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOfflineMessagesResponse)
	err := c.cc.Invoke(ctx, IM_ListOfflineMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMClient) AckOfflineMessages(ctx context.Context, in *AckOfflineMessagesRequest, opts ...grpc.CallOption) (*AckOfflineMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckOfflineMessagesResponse)
	err := c.cc.Invoke(ctx, IM_AckOfflineMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMServer is the server API for IM service.
// All implementations must embed UnimplementedIMServer
// for forward compatibility.
type IMServer interface {
	// 从 authorization metadata 确定用户，检查其是否属于群及所属团队。
	CheckGroupMember(context.Context, *CheckGroupMemberRequest) (*CheckGroupMemberResponse, error)
	// 核对当前用户属于指定团队中的指定群，不读取消息正文。
	CheckTeamGroupAccess(context.Context, *CheckTeamGroupAccessRequest) (*CheckTeamGroupAccessResponse, error)
	// 团队拥有者创建团队群，并加入为群主。
	CreateTeamGroup(context.Context, *CreateTeamGroupRequest) (*CreateTeamGroupResponse, error)
	// 团队成员分页查看所属团队的群。
	ListTeamGroups(context.Context, *ListTeamGroupsRequest) (*ListTeamGroupsResponse, error)
	// 当前团队成员自行加入所属团队的群；用户身份从 authorization 获取。
	JoinTeamGroup(context.Context, *JoinTeamGroupRequest) (*JoinTeamGroupResponse, error)
	// 团队群成员按消息 ID 倒序读取历史消息。
	ListTeamGroupMessages(context.Context, *ListTeamGroupMessagesRequest) (*ListTeamGroupMessagesResponse, error)
	// 本人当前团队群未读数；读取不标已读。
	GetTeamGroupUnread(context.Context, *GetTeamGroupUnreadRequest) (*GetTeamGroupUnreadResponse, error)
	// 明确确认已加载的具体消息；不使用消息ID高水位。
	MarkTeamGroupMessagesRead(context.Context, *MarkTeamGroupMessagesReadRequest) (*MarkTeamGroupMessagesReadResponse, error)
	// 本人和指定对方的单聊历史，按消息 ID 倒序分页。
	ListDirectMessages(context.Context, *ListDirectMessagesRequest) (*ListDirectMessagesResponse, error)
	// 本人收到该对方消息的未读数；读取不标已读。
	GetDirectUnread(context.Context, *GetDirectUnreadRequest) (*GetDirectUnreadResponse, error)
	// 本人显式确认该对方发来的具体消息。
	MarkDirectMessagesRead(context.Context, *MarkDirectMessagesReadRequest) (*MarkDirectMessagesReadResponse, error)
	// 核对当前用户可访问指定团队群中的来源消息，供任务服务建立引用。
	CheckTeamGroupMessage(context.Context, *CheckTeamGroupMessageRequest) (*CheckTeamGroupMessageResponse, error)
	// 从 authorization metadata 确定本人，只读拉取尚未确认的离线消息。
	ListOfflineMessages(context.Context, *ListOfflineMessagesRequest) (*ListOfflineMessagesResponse, error)
	// 当前用户处理完消息后，按消息 ID 确认离线投递。
	AckOfflineMessages(context.Context, *AckOfflineMessagesRequest) (*AckOfflineMessagesResponse, error)
	mustEmbedUnimplementedIMServer()
}

// UnimplementedIMServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIMServer struct{}

func (UnimplementedIMServer) CheckGroupMember(context.Context, *CheckGroupMemberRequest) (*CheckGroupMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckGroupMember not implemented")
}
func (UnimplementedIMServer) CheckTeamGroupAccess(context.Context, *CheckTeamGroupAccessRequest) (*CheckTeamGroupAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTeamGroupAccess not implemented")
}
func (UnimplementedIMServer) CreateTeamGroup(context.Context, *CreateTeamGroupRequest) (*CreateTeamGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeamGroup not implemented")
}
func (UnimplementedIMServer) ListTeamGroups(context.Context, *ListTeamGroupsRequest) (*ListTeamGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTeamGroups not implemented")
}
func (UnimplementedIMServer) JoinTeamGroup(context.Context, *JoinTeamGroupRequest) (*JoinTeamGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinTeamGroup not implemented")
}
func (UnimplementedIMServer) ListTeamGroupMessages(context.Context, *ListTeamGroupMessagesRequest) (*ListTeamGroupMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTeamGroupMessages not implemented")
}
func (UnimplementedIMServer) GetTeamGroupUnread(context.Context, *GetTeamGroupUnreadRequest) (*GetTeamGroupUnreadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamGroupUnread not implemented")
}
func (UnimplementedIMServer) MarkTeamGroupMessagesRead(context.Context, *MarkTeamGroupMessagesReadRequest) (*MarkTeamGroupMessagesReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkTeamGroupMessagesRead not implemented")
}
func (UnimplementedIMServer) ListDirectMessages(context.Context, *ListDirectMessagesRequest) (*ListDirectMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDirectMessages not implemented")
}
func (UnimplementedIMServer) GetDirectUnread(context.Context, *GetDirectUnreadRequest) (*GetDirectUnreadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirectUnread not implemented")
}
func (UnimplementedIMServer) MarkDirectMessagesRead(context.Context, *MarkDirectMessagesReadRequest) (*MarkDirectMessagesReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkDirectMessagesRead not implemented")
}
func (UnimplementedIMServer) CheckTeamGroupMessage(context.Context, *CheckTeamGroupMessageRequest) (*CheckTeamGroupMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTeamGroupMessage not implemented")
}
func (UnimplementedIMServer) ListOfflineMessages(context.Context, *ListOfflineMessagesRequest) (*ListOfflineMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOfflineMessages not implemented")
}
func (UnimplementedIMServer) AckOfflineMessages(context.Context, *AckOfflineMessagesRequest) (*AckOfflineMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckOfflineMessages not implemented")
}
func (UnimplementedIMServer) mustEmbedUnimplementedIMServer() {}
func (UnimplementedIMServer) testEmbeddedByValue()            {}

// UnsafeIMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMServer will
// result in compilation errors.
type UnsafeIMServer interface {
	mustEmbedUnimplementedIMServer()
}

func RegisterIMServer(s grpc.ServiceRegistrar, srv IMServer) {
	// If the following call pancis, it indicates UnimplementedIMServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IM_ServiceDesc, srv)
}

func _IM_CheckGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckGroupMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).CheckGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_CheckGroupMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).CheckGroupMember(ctx, req.(*CheckGroupMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_CheckTeamGroupAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTeamGroupAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).CheckTeamGroupAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_CheckTeamGroupAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).CheckTeamGroupAccess(ctx, req.(*CheckTeamGroupAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_CreateTeamGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).CreateTeamGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_CreateTeamGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).CreateTeamGroup(ctx, req.(*CreateTeamGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_ListTeamGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).ListTeamGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_ListTeamGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).ListTeamGroups(ctx, req.(*ListTeamGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_JoinTeamGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinTeamGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).JoinTeamGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_JoinTeamGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).JoinTeamGroup(ctx, req.(*JoinTeamGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_ListTeamGroupMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamGroupMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).ListTeamGroupMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_ListTeamGroupMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).ListTeamGroupMessages(ctx, req.(*ListTeamGroupMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_GetTeamGroupUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamGroupUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).GetTeamGroupUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_GetTeamGroupUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).GetTeamGroupUnread(ctx, req.(*GetTeamGroupUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_MarkTeamGroupMessagesRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkTeamGroupMessagesReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).MarkTeamGroupMessagesRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_MarkTeamGroupMessagesRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).MarkTeamGroupMessagesRead(ctx, req.(*MarkTeamGroupMessagesReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_ListDirectMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).ListDirectMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_ListDirectMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).ListDirectMessages(ctx, req.(*ListDirectMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_GetDirectUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).GetDirectUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_GetDirectUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).GetDirectUnread(ctx, req.(*GetDirectUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_MarkDirectMessagesRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkDirectMessagesReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).MarkDirectMessagesRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_MarkDirectMessagesRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).MarkDirectMessagesRead(ctx, req.(*MarkDirectMessagesReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_CheckTeamGroupMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTeamGroupMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).CheckTeamGroupMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_CheckTeamGroupMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).CheckTeamGroupMessage(ctx, req.(*CheckTeamGroupMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_ListOfflineMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOfflineMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).ListOfflineMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_ListOfflineMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).ListOfflineMessages(ctx, req.(*ListOfflineMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IM_AckOfflineMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckOfflineMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServer).AckOfflineMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IM_AckOfflineMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServer).AckOfflineMessages(ctx, req.(*AckOfflineMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IM_ServiceDesc is the grpc.ServiceDesc for IM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "im.IM",
	HandlerType: (*IMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckGroupMember",
			Handler:    _IM_CheckGroupMember_Handler,
		},
		{
			MethodName: "CheckTeamGroupAccess",
			Handler:    _IM_CheckTeamGroupAccess_Handler,
		},
		{
			MethodName: "CreateTeamGroup",
			Handler:    _IM_CreateTeamGroup_Handler,
		},
		{
			MethodName: "ListTeamGroups",
			Handler:    _IM_ListTeamGroups_Handler,
		},
		{
			MethodName: "JoinTeamGroup",
			Handler:    _IM_JoinTeamGroup_Handler,
		},
		{
			MethodName: "ListTeamGroupMessages",
			Handler:    _IM_ListTeamGroupMessages_Handler,
		},
		{
			MethodName: "GetTeamGroupUnread",
			Handler:    _IM_GetTeamGroupUnread_Handler,
		},
		{
			MethodName: "MarkTeamGroupMessagesRead",
			Handler:    _IM_MarkTeamGroupMessagesRead_Handler,
		},
		{
			MethodName: "ListDirectMessages",
			Handler:    _IM_ListDirectMessages_Handler,
		},
		{
			MethodName: "GetDirectUnread",
			Handler:    _IM_GetDirectUnread_Handler,
		},
		{
			MethodName: "MarkDirectMessagesRead",
			Handler:    _IM_MarkDirectMessagesRead_Handler,
		},
		{
			MethodName: "CheckTeamGroupMessage",
			Handler:    _IM_CheckTeamGroupMessage_Handler,
		},
		{
			MethodName: "ListOfflineMessages",
			Handler:    _IM_ListOfflineMessages_Handler,
		},
		{
			MethodName: "AckOfflineMessages",
			Handler:    _IM_AckOfflineMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/im/im.proto",
}
