// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: leave.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IMLeave_CloseTeamGroupMemberships_FullMethodName = "/im.IMLeave/CloseTeamGroupMemberships"
)

// IMLeaveClient is the client API for IMLeave service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dedicated mTLS service for User-owned team leave operations.
// Never register it on ordinary IM, bot, or Agent trigger listeners.
type IMLeaveClient interface {
	CloseTeamGroupMemberships(ctx context.Context, in *CloseTeamGroupMembershipsRequest, opts ...grpc.CallOption) (*CloseTeamGroupMembershipsResponse, error)
}

type iMLeaveClient struct {
	cc grpc.ClientConnInterface
}

func NewIMLeaveClient(cc grpc.ClientConnInterface) IMLeaveClient {
	return &iMLeaveClient{cc}
}

func (c *iMLeaveClient) CloseTeamGroupMemberships(ctx context.Context, in *CloseTeamGroupMembershipsRequest, opts ...grpc.CallOption) (*CloseTeamGroupMembershipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseTeamGroupMembershipsResponse)
	err := c.cc.Invoke(ctx, IMLeave_CloseTeamGroupMemberships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMLeaveServer is the server API for IMLeave service.
// All implementations must embed UnimplementedIMLeaveServer
// for forward compatibility.
//
// Dedicated mTLS service for User-owned team leave operations.
// Never register it on ordinary IM, bot, or Agent trigger listeners.
type IMLeaveServer interface {
	CloseTeamGroupMemberships(context.Context, *CloseTeamGroupMembershipsRequest) (*CloseTeamGroupMembershipsResponse, error)
	mustEmbedUnimplementedIMLeaveServer()
}

// UnimplementedIMLeaveServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIMLeaveServer struct{}

func (UnimplementedIMLeaveServer) CloseTeamGroupMemberships(context.Context, *CloseTeamGroupMembershipsRequest) (*CloseTeamGroupMembershipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseTeamGroupMemberships not implemented")
}
func (UnimplementedIMLeaveServer) mustEmbedUnimplementedIMLeaveServer() {}
func (UnimplementedIMLeaveServer) testEmbeddedByValue()                 {}

// UnsafeIMLeaveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMLeaveServer will
// result in compilation errors.
type UnsafeIMLeaveServer interface {
	mustEmbedUnimplementedIMLeaveServer()
}

func RegisterIMLeaveServer(s grpc.ServiceRegistrar, srv IMLeaveServer) {
	// If the following call pancis, it indicates UnimplementedIMLeaveServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IMLeave_ServiceDesc, srv)
}

func _IMLeave_CloseTeamGroupMemberships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseTeamGroupMembershipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMLeaveServer).CloseTeamGroupMemberships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMLeave_CloseTeamGroupMemberships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMLeaveServer).CloseTeamGroupMemberships(ctx, req.(*CloseTeamGroupMembershipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IMLeave_ServiceDesc is the grpc.ServiceDesc for IMLeave service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMLeave_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "im.IMLeave",
	HandlerType: (*IMLeaveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloseTeamGroupMemberships",
			Handler:    _IMLeave_CloseTeamGroupMemberships_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leave.proto",
}
