// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: rpc/im/mention.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MentionMemberGeneration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamGeneration int64                  `protobuf:"varint,2,opt,name=team_generation,json=teamGeneration,proto3" json:"team_generation,omitempty"` // Verified by User's Push-only service.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MentionMemberGeneration) Reset() {
	*x = MentionMemberGeneration{}
	mi := &file_rpc_im_mention_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentionMemberGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentionMemberGeneration) ProtoMessage() {}

func (x *MentionMemberGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_mention_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentionMemberGeneration.ProtoReflect.Descriptor instead.
func (*MentionMemberGeneration) Descriptor() ([]byte, []int) {
	return file_rpc_im_mention_proto_rawDescGZIP(), []int{0}
}

func (x *MentionMemberGeneration) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MentionMemberGeneration) GetTeamGeneration() int64 {
	if x != nil {
		return x.TeamGeneration
	}
	return 0
}

type ValidateGroupMentionTargetsRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	GroupId       int64                      `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Sender        *MentionMemberGeneration   `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Targets       []*MentionMemberGeneration `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"` // 1..10 distinct users.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateGroupMentionTargetsRequest) Reset() {
	*x = ValidateGroupMentionTargetsRequest{}
	mi := &file_rpc_im_mention_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateGroupMentionTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateGroupMentionTargetsRequest) ProtoMessage() {}

func (x *ValidateGroupMentionTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_mention_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateGroupMentionTargetsRequest.ProtoReflect.Descriptor instead.
func (*ValidateGroupMentionTargetsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_mention_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateGroupMentionTargetsRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ValidateGroupMentionTargetsRequest) GetSender() *MentionMemberGeneration {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *ValidateGroupMentionTargetsRequest) GetTargets() []*MentionMemberGeneration {
	if x != nil {
		return x.Targets
	}
	return nil
}

type ValidateGroupMentionTargetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateGroupMentionTargetsResponse) Reset() {
	*x = ValidateGroupMentionTargetsResponse{}
	mi := &file_rpc_im_mention_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateGroupMentionTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateGroupMentionTargetsResponse) ProtoMessage() {}

func (x *ValidateGroupMentionTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_mention_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateGroupMentionTargetsResponse.ProtoReflect.Descriptor instead.
func (*ValidateGroupMentionTargetsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_mention_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateGroupMentionTargetsResponse) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

var File_rpc_im_mention_proto protoreflect.FileDescriptor

const file_rpc_im_mention_proto_rawDesc = "" +
	"\n" +
	"\x14rpc/im/mention.proto\x12\x02im\"[\n" +
	"\x17MentionMemberGeneration\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fteam_generation\x18\x02 \x01(\x03R\x0eteamGeneration\"\xab\x01\n" +
	"\"ValidateGroupMentionTargetsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x123\n" +
	"\x06sender\x18\x02 \x01(\v2\x1b.im.MentionMemberGenerationR\x06sender\x125\n" +
	"\atargets\x18\x03 \x03(\v2\x1b.im.MentionMemberGenerationR\atargets\">\n" +
	"#ValidateGroupMentionTargetsResponse\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId2{\n" +
	"\tIMMention\x12n\n" +
	"\x1bValidateGroupMentionTargets\x12&.im.ValidateGroupMentionTargetsRequest\x1a'.im.ValidateGroupMentionTargetsResponseB$Z\"github.com/yjydist/go-im/rpc/im/pbb\x06proto3"

var (
	file_rpc_im_mention_proto_rawDescOnce sync.Once
	file_rpc_im_mention_proto_rawDescData []byte
)

func file_rpc_im_mention_proto_rawDescGZIP() []byte {
	file_rpc_im_mention_proto_rawDescOnce.Do(func() {
		file_rpc_im_mention_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_im_mention_proto_rawDesc), len(file_rpc_im_mention_proto_rawDesc)))
	})
	return file_rpc_im_mention_proto_rawDescData
}

var file_rpc_im_mention_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_im_mention_proto_goTypes = []any{
	(*MentionMemberGeneration)(nil),             // 0: im.MentionMemberGeneration
	(*ValidateGroupMentionTargetsRequest)(nil),  // 1: im.ValidateGroupMentionTargetsRequest
	(*ValidateGroupMentionTargetsResponse)(nil), // 2: im.ValidateGroupMentionTargetsResponse
}
var file_rpc_im_mention_proto_depIdxs = []int32{
	0, // 0: im.ValidateGroupMentionTargetsRequest.sender:type_name -> im.MentionMemberGeneration
	0, // 1: im.ValidateGroupMentionTargetsRequest.targets:type_name -> im.MentionMemberGeneration
	1, // 2: im.IMMention.ValidateGroupMentionTargets:input_type -> im.ValidateGroupMentionTargetsRequest
	2, // 3: im.IMMention.ValidateGroupMentionTargets:output_type -> im.ValidateGroupMentionTargetsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_im_mention_proto_init() }
func file_rpc_im_mention_proto_init() {
	if File_rpc_im_mention_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_im_mention_proto_rawDesc), len(file_rpc_im_mention_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_im_mention_proto_goTypes,
		DependencyIndexes: file_rpc_im_mention_proto_depIdxs,
		MessageInfos:      file_rpc_im_mention_proto_msgTypes,
	}.Build()
	File_rpc_im_mention_proto = out.File
	file_rpc_im_mention_proto_goTypes = nil
	file_rpc_im_mention_proto_depIdxs = nil
}
