// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: rpc/im/mention.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IMMention_ValidateGroupMentionTargets_FullMethodName = "/im.IMMention/ValidateGroupMentionTargets"
)

// IMMentionClient is the client API for IMMention service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Registered only on a dedicated mTLS listener accepting the Push identity.
type IMMentionClient interface {
	ValidateGroupMentionTargets(ctx context.Context, in *ValidateGroupMentionTargetsRequest, opts ...grpc.CallOption) (*ValidateGroupMentionTargetsResponse, error)
}

type iMMentionClient struct {
	cc grpc.ClientConnInterface
}

func NewIMMentionClient(cc grpc.ClientConnInterface) IMMentionClient {
	return &iMMentionClient{cc}
}

func (c *iMMentionClient) ValidateGroupMentionTargets(ctx context.Context, in *ValidateGroupMentionTargetsRequest, opts ...grpc.CallOption) (*ValidateGroupMentionTargetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateGroupMentionTargetsResponse)
	err := c.cc.Invoke(ctx, IMMention_ValidateGroupMentionTargets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMMentionServer is the server API for IMMention service.
// All implementations must embed UnimplementedIMMentionServer
// for forward compatibility.
//
// Registered only on a dedicated mTLS listener accepting the Push identity.
type IMMentionServer interface {
	ValidateGroupMentionTargets(context.Context, *ValidateGroupMentionTargetsRequest) (*ValidateGroupMentionTargetsResponse, error)
	mustEmbedUnimplementedIMMentionServer()
}

// UnimplementedIMMentionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIMMentionServer struct{}

func (UnimplementedIMMentionServer) ValidateGroupMentionTargets(context.Context, *ValidateGroupMentionTargetsRequest) (*ValidateGroupMentionTargetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateGroupMentionTargets not implemented")
}
func (UnimplementedIMMentionServer) mustEmbedUnimplementedIMMentionServer() {}
func (UnimplementedIMMentionServer) testEmbeddedByValue()                   {}

// UnsafeIMMentionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMMentionServer will
// result in compilation errors.
type UnsafeIMMentionServer interface {
	mustEmbedUnimplementedIMMentionServer()
}

func RegisterIMMentionServer(s grpc.ServiceRegistrar, srv IMMentionServer) {
	// If the following call pancis, it indicates UnimplementedIMMentionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IMMention_ServiceDesc, srv)
}

func _IMMention_ValidateGroupMentionTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateGroupMentionTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMMentionServer).ValidateGroupMentionTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMMention_ValidateGroupMentionTargets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMMentionServer).ValidateGroupMentionTargets(ctx, req.(*ValidateGroupMentionTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IMMention_ServiceDesc is the grpc.ServiceDesc for IMMention service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMMention_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "im.IMMention",
	HandlerType: (*IMMentionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateGroupMentionTargets",
			Handler:    _IMMention_ValidateGroupMentionTargets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/im/mention.proto",
}
