// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: rpc/im/trigger.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IMTrigger_ReadTaskTriggerContext_FullMethodName   = "/im.IMTrigger/ReadTaskTriggerContext"
	IMTrigger_ResolveTaskTriggerMember_FullMethodName = "/im.IMTrigger/ResolveTaskTriggerMember"
)

// IMTriggerClient is the client API for IMTrigger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dedicated mTLS service. Never registered on the ordinary IM or bot port.
type IMTriggerClient interface {
	ReadTaskTriggerContext(ctx context.Context, in *ReadTaskTriggerContextRequest, opts ...grpc.CallOption) (*ReadTaskTriggerContextResponse, error)
	ResolveTaskTriggerMember(ctx context.Context, in *ResolveTaskTriggerMemberRequest, opts ...grpc.CallOption) (*ResolveTaskTriggerMemberResponse, error)
}

type iMTriggerClient struct {
	cc grpc.ClientConnInterface
}

func NewIMTriggerClient(cc grpc.ClientConnInterface) IMTriggerClient {
	return &iMTriggerClient{cc}
}

func (c *iMTriggerClient) ReadTaskTriggerContext(ctx context.Context, in *ReadTaskTriggerContextRequest, opts ...grpc.CallOption) (*ReadTaskTriggerContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadTaskTriggerContextResponse)
	err := c.cc.Invoke(ctx, IMTrigger_ReadTaskTriggerContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMTriggerClient) ResolveTaskTriggerMember(ctx context.Context, in *ResolveTaskTriggerMemberRequest, opts ...grpc.CallOption) (*ResolveTaskTriggerMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveTaskTriggerMemberResponse)
	err := c.cc.Invoke(ctx, IMTrigger_ResolveTaskTriggerMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMTriggerServer is the server API for IMTrigger service.
// All implementations must embed UnimplementedIMTriggerServer
// for forward compatibility.
//
// Dedicated mTLS service. Never registered on the ordinary IM or bot port.
type IMTriggerServer interface {
	ReadTaskTriggerContext(context.Context, *ReadTaskTriggerContextRequest) (*ReadTaskTriggerContextResponse, error)
	ResolveTaskTriggerMember(context.Context, *ResolveTaskTriggerMemberRequest) (*ResolveTaskTriggerMemberResponse, error)
	mustEmbedUnimplementedIMTriggerServer()
}

// UnimplementedIMTriggerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIMTriggerServer struct{}

func (UnimplementedIMTriggerServer) ReadTaskTriggerContext(context.Context, *ReadTaskTriggerContextRequest) (*ReadTaskTriggerContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTaskTriggerContext not implemented")
}
func (UnimplementedIMTriggerServer) ResolveTaskTriggerMember(context.Context, *ResolveTaskTriggerMemberRequest) (*ResolveTaskTriggerMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveTaskTriggerMember not implemented")
}
func (UnimplementedIMTriggerServer) mustEmbedUnimplementedIMTriggerServer() {}
func (UnimplementedIMTriggerServer) testEmbeddedByValue()                   {}

// UnsafeIMTriggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMTriggerServer will
// result in compilation errors.
type UnsafeIMTriggerServer interface {
	mustEmbedUnimplementedIMTriggerServer()
}

func RegisterIMTriggerServer(s grpc.ServiceRegistrar, srv IMTriggerServer) {
	// If the following call pancis, it indicates UnimplementedIMTriggerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IMTrigger_ServiceDesc, srv)
}

func _IMTrigger_ReadTaskTriggerContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTaskTriggerContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMTriggerServer).ReadTaskTriggerContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMTrigger_ReadTaskTriggerContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMTriggerServer).ReadTaskTriggerContext(ctx, req.(*ReadTaskTriggerContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMTrigger_ResolveTaskTriggerMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveTaskTriggerMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMTriggerServer).ResolveTaskTriggerMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMTrigger_ResolveTaskTriggerMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMTriggerServer).ResolveTaskTriggerMember(ctx, req.(*ResolveTaskTriggerMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IMTrigger_ServiceDesc is the grpc.ServiceDesc for IMTrigger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMTrigger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "im.IMTrigger",
	HandlerType: (*IMTriggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadTaskTriggerContext",
			Handler:    _IMTrigger_ReadTaskTriggerContext_Handler,
		},
		{
			MethodName: "ResolveTaskTriggerMember",
			Handler:    _IMTrigger_ResolveTaskTriggerMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/im/trigger.proto",
}
