// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: rpc/im/trigger.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadTaskTriggerContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskTriggerContextRequest) Reset() {
	*x = ReadTaskTriggerContextRequest{}
	mi := &file_rpc_im_trigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskTriggerContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskTriggerContextRequest) ProtoMessage() {}

func (x *ReadTaskTriggerContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_trigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskTriggerContextRequest.ProtoReflect.Descriptor instead.
func (*ReadTaskTriggerContextRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *ReadTaskTriggerContextRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type ReadTaskTriggerContextResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MessageId           int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MsgId               string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ActorId             int64                  `protobuf:"varint,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	TeamId              int64                  `protobuf:"varint,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId             int64                  `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Instruction         string                 `protobuf:"bytes,6,opt,name=instruction,proto3" json:"instruction,omitempty"`
	ReferenceTimeUnixMs int64                  `protobuf:"varint,7,opt,name=reference_time_unix_ms,json=referenceTimeUnixMs,proto3" json:"reference_time_unix_ms,omitempty"`
	RequestKey          string                 `protobuf:"bytes,8,opt,name=request_key,json=requestKey,proto3" json:"request_key,omitempty"`
	// At most 20 messages, descending IDs <= the trigger ID; includes the source.
	Messages      []*TeamGroupMessage `protobuf:"bytes,9,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskTriggerContextResponse) Reset() {
	*x = ReadTaskTriggerContextResponse{}
	mi := &file_rpc_im_trigger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskTriggerContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskTriggerContextResponse) ProtoMessage() {}

func (x *ReadTaskTriggerContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_trigger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskTriggerContextResponse.ProtoReflect.Descriptor instead.
func (*ReadTaskTriggerContextResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_trigger_proto_rawDescGZIP(), []int{1}
}

func (x *ReadTaskTriggerContextResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ReadTaskTriggerContextResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ReadTaskTriggerContextResponse) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *ReadTaskTriggerContextResponse) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ReadTaskTriggerContextResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ReadTaskTriggerContextResponse) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *ReadTaskTriggerContextResponse) GetReferenceTimeUnixMs() int64 {
	if x != nil {
		return x.ReferenceTimeUnixMs
	}
	return 0
}

func (x *ReadTaskTriggerContextResponse) GetRequestKey() string {
	if x != nil {
		return x.RequestKey
	}
	return ""
}

func (x *ReadTaskTriggerContextResponse) GetMessages() []*TeamGroupMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_rpc_im_trigger_proto protoreflect.FileDescriptor

const file_rpc_im_trigger_proto_rawDesc = "" +
	"\n" +
	"\x14rpc/im/trigger.proto\x12\x02im\x1a\x0frpc/im/im.proto\">\n" +
	"\x1dReadTaskTriggerContextRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"\xcf\x02\n" +
	"\x1eReadTaskTriggerContextResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\x03R\aactorId\x12\x17\n" +
	"\ateam_id\x18\x04 \x01(\x03R\x06teamId\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\x03R\agroupId\x12 \n" +
	"\vinstruction\x18\x06 \x01(\tR\vinstruction\x123\n" +
	"\x16reference_time_unix_ms\x18\a \x01(\x03R\x13referenceTimeUnixMs\x12\x1f\n" +
	"\vrequest_key\x18\b \x01(\tR\n" +
	"requestKey\x120\n" +
	"\bmessages\x18\t \x03(\v2\x14.im.TeamGroupMessageR\bmessages2l\n" +
	"\tIMTrigger\x12_\n" +
	"\x16ReadTaskTriggerContext\x12!.im.ReadTaskTriggerContextRequest\x1a\".im.ReadTaskTriggerContextResponseB$Z\"github.com/yjydist/go-im/rpc/im/pbb\x06proto3"

var (
	file_rpc_im_trigger_proto_rawDescOnce sync.Once
	file_rpc_im_trigger_proto_rawDescData []byte
)

func file_rpc_im_trigger_proto_rawDescGZIP() []byte {
	file_rpc_im_trigger_proto_rawDescOnce.Do(func() {
		file_rpc_im_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_im_trigger_proto_rawDesc), len(file_rpc_im_trigger_proto_rawDesc)))
	})
	return file_rpc_im_trigger_proto_rawDescData
}

var file_rpc_im_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_im_trigger_proto_goTypes = []any{
	(*ReadTaskTriggerContextRequest)(nil),  // 0: im.ReadTaskTriggerContextRequest
	(*ReadTaskTriggerContextResponse)(nil), // 1: im.ReadTaskTriggerContextResponse
	(*TeamGroupMessage)(nil),               // 2: im.TeamGroupMessage
}
var file_rpc_im_trigger_proto_depIdxs = []int32{
	2, // 0: im.ReadTaskTriggerContextResponse.messages:type_name -> im.TeamGroupMessage
	0, // 1: im.IMTrigger.ReadTaskTriggerContext:input_type -> im.ReadTaskTriggerContextRequest
	1, // 2: im.IMTrigger.ReadTaskTriggerContext:output_type -> im.ReadTaskTriggerContextResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_im_trigger_proto_init() }
func file_rpc_im_trigger_proto_init() {
	if File_rpc_im_trigger_proto != nil {
		return
	}
	file_rpc_im_im_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_im_trigger_proto_rawDesc), len(file_rpc_im_trigger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_im_trigger_proto_goTypes,
		DependencyIndexes: file_rpc_im_trigger_proto_depIdxs,
		MessageInfos:      file_rpc_im_trigger_proto_msgTypes,
	}.Build()
	File_rpc_im_trigger_proto = out.File
	file_rpc_im_trigger_proto_goTypes = nil
	file_rpc_im_trigger_proto_depIdxs = nil
}
