// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_Ask_FullMethodName              = "/agent.Agent/Ask"
	Agent_GetTaskDraft_FullMethodName     = "/agent.Agent/GetTaskDraft"
	Agent_PrepareTaskDraft_FullMethodName = "/agent.Agent/PrepareTaskDraft"
	Agent_EditTaskDraft_FullMethodName    = "/agent.Agent/EditTaskDraft"
	Agent_ConfirmTaskDraft_FullMethodName = "/agent.Agent/ConfirmTaskDraft"
	Agent_RetryTaskReply_FullMethodName   = "/agent.Agent/RetryTaskReply"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	// authorization: Bearer <token> 经 gRPC metadata 传入；第一版只读问答。
	Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error)
	// 仅草稿发起人可读取；每次读取都重新校验当前团队群资格。
	GetTaskDraft(ctx context.Context, in *GetTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error)
	// 显式生成一项待确认草稿；authorization 与 idempotency-key 经 metadata 传入。
	PrepareTaskDraft(ctx context.Context, in *PrepareTaskDraftRequest, opts ...grpc.CallOption) (*PrepareTaskDraftResponse, error)
	// 仅发起人可修改待确认草稿的标题和说明；每次重新校验当前团队群资格。
	EditTaskDraft(ctx context.Context, in *EditTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error)
	// 仅发起人可确认；冻结内容及服务端请求键，重复请求复用原任务。
	ConfirmTaskDraft(ctx context.Context, in *ConfirmTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error)
	// 仅本人显式重试原回帖；不重新创建任务，不接受任意正文或群范围。
	RetryTaskReply(ctx context.Context, in *GetTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskResponse)
	err := c.cc.Invoke(ctx, Agent_Ask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetTaskDraft(ctx context.Context, in *GetTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_GetTaskDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PrepareTaskDraft(ctx context.Context, in *PrepareTaskDraftRequest, opts ...grpc.CallOption) (*PrepareTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_PrepareTaskDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) EditTaskDraft(ctx context.Context, in *EditTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_EditTaskDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ConfirmTaskDraft(ctx context.Context, in *ConfirmTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_ConfirmTaskDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RetryTaskReply(ctx context.Context, in *GetTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_RetryTaskReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
type AgentServer interface {
	// authorization: Bearer <token> 经 gRPC metadata 传入；第一版只读问答。
	Ask(context.Context, *AskRequest) (*AskResponse, error)
	// 仅草稿发起人可读取；每次读取都重新校验当前团队群资格。
	GetTaskDraft(context.Context, *GetTaskDraftRequest) (*GetTaskDraftResponse, error)
	// 显式生成一项待确认草稿；authorization 与 idempotency-key 经 metadata 传入。
	PrepareTaskDraft(context.Context, *PrepareTaskDraftRequest) (*PrepareTaskDraftResponse, error)
	// 仅发起人可修改待确认草稿的标题和说明；每次重新校验当前团队群资格。
	EditTaskDraft(context.Context, *EditTaskDraftRequest) (*GetTaskDraftResponse, error)
	// 仅发起人可确认；冻结内容及服务端请求键，重复请求复用原任务。
	ConfirmTaskDraft(context.Context, *ConfirmTaskDraftRequest) (*GetTaskDraftResponse, error)
	// 仅本人显式重试原回帖；不重新创建任务，不接受任意正文或群范围。
	RetryTaskReply(context.Context, *GetTaskDraftRequest) (*GetTaskDraftResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) Ask(context.Context, *AskRequest) (*AskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedAgentServer) GetTaskDraft(context.Context, *GetTaskDraftRequest) (*GetTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskDraft not implemented")
}
func (UnimplementedAgentServer) PrepareTaskDraft(context.Context, *PrepareTaskDraftRequest) (*PrepareTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareTaskDraft not implemented")
}
func (UnimplementedAgentServer) EditTaskDraft(context.Context, *EditTaskDraftRequest) (*GetTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTaskDraft not implemented")
}
func (UnimplementedAgentServer) ConfirmTaskDraft(context.Context, *ConfirmTaskDraftRequest) (*GetTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTaskDraft not implemented")
}
func (UnimplementedAgentServer) RetryTaskReply(context.Context, *GetTaskDraftRequest) (*GetTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryTaskReply not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call pancis, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Ask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Ask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Ask(ctx, req.(*AskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetTaskDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetTaskDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetTaskDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetTaskDraft(ctx, req.(*GetTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PrepareTaskDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PrepareTaskDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PrepareTaskDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PrepareTaskDraft(ctx, req.(*PrepareTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_EditTaskDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).EditTaskDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_EditTaskDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).EditTaskDraft(ctx, req.(*EditTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ConfirmTaskDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ConfirmTaskDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ConfirmTaskDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ConfirmTaskDraft(ctx, req.(*ConfirmTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RetryTaskReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RetryTaskReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RetryTaskReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RetryTaskReply(ctx, req.(*GetTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ask",
			Handler:    _Agent_Ask_Handler,
		},
		{
			MethodName: "GetTaskDraft",
			Handler:    _Agent_GetTaskDraft_Handler,
		},
		{
			MethodName: "PrepareTaskDraft",
			Handler:    _Agent_PrepareTaskDraft_Handler,
		},
		{
			MethodName: "EditTaskDraft",
			Handler:    _Agent_EditTaskDraft_Handler,
		},
		{
			MethodName: "ConfirmTaskDraft",
			Handler:    _Agent_ConfirmTaskDraft_Handler,
		},
		{
			MethodName: "RetryTaskReply",
			Handler:    _Agent_RetryTaskReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
