// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_Ask_FullMethodName                         = "/agent.Agent/Ask"
	Agent_GetTaskDraft_FullMethodName                = "/agent.Agent/GetTaskDraft"
	Agent_PrepareTaskDraft_FullMethodName            = "/agent.Agent/PrepareTaskDraft"
	Agent_EditTaskDraft_FullMethodName               = "/agent.Agent/EditTaskDraft"
	Agent_SelectTaskDraftAssignee_FullMethodName     = "/agent.Agent/SelectTaskDraftAssignee"
	Agent_EditTaskDraftDeadline_FullMethodName       = "/agent.Agent/EditTaskDraftDeadline"
	Agent_ConfirmTaskDraft_FullMethodName            = "/agent.Agent/ConfirmTaskDraft"
	Agent_RetryTaskReply_FullMethodName              = "/agent.Agent/RetryTaskReply"
	Agent_PrepareTaskDraftCollection_FullMethodName  = "/agent.Agent/PrepareTaskDraftCollection"
	Agent_GetTaskDraftCollection_FullMethodName      = "/agent.Agent/GetTaskDraftCollection"
	Agent_GetTaskDraftItem_FullMethodName            = "/agent.Agent/GetTaskDraftItem"
	Agent_EditTaskDraftItemText_FullMethodName       = "/agent.Agent/EditTaskDraftItemText"
	Agent_SelectTaskDraftItemAssignee_FullMethodName = "/agent.Agent/SelectTaskDraftItemAssignee"
	Agent_EditTaskDraftItemDeadline_FullMethodName   = "/agent.Agent/EditTaskDraftItemDeadline"
	Agent_ConfirmTaskDraftItem_FullMethodName        = "/agent.Agent/ConfirmTaskDraftItem"
	Agent_SkipTaskDraftItem_FullMethodName           = "/agent.Agent/SkipTaskDraftItem"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	// authorization: Bearer <token> 经 gRPC metadata 传入；第一版只读问答。
	Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error)
	// 仅草稿发起人可读取；每次读取都重新校验当前团队群资格。
	GetTaskDraft(ctx context.Context, in *GetTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error)
	// 显式生成一项待确认草稿；authorization 与 idempotency-key 经 metadata 传入。
	PrepareTaskDraft(ctx context.Context, in *PrepareTaskDraftRequest, opts ...grpc.CallOption) (*PrepareTaskDraftResponse, error)
	// 仅发起人可修改待确认草稿的标题和说明；每次重新校验当前团队群资格。
	EditTaskDraft(ctx context.Context, in *EditTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error)
	// 本人明确选择当前团队成员或未指派；必须携带读取的内容版本。
	SelectTaskDraftAssignee(ctx context.Context, in *SelectTaskDraftAssigneeRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error)
	// 本人编辑已保存草稿截止时间；0 明确清除，缺字段拒绝，冻结后不可改。
	EditTaskDraftDeadline(ctx context.Context, in *EditTaskDraftDeadlineRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error)
	// 仅发起人可确认；冻结内容及服务端请求键，重复请求复用原任务。
	ConfirmTaskDraft(ctx context.Context, in *ConfirmTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error)
	// 仅本人显式重试原回帖；不重新创建任务，不接受任意正文或群范围。
	RetryTaskReply(ctx context.Context, in *GetTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error)
	// 一次生成并原子保存1..5项候选；和旧单项生成区分请求意图。
	PrepareTaskDraftCollection(ctx context.Context, in *PrepareTaskDraftRequest, opts ...grpc.CallOption) (*PrepareTaskDraftResponse, error)
	// 仅发起人可读完整集合，每次重新核对当前团队群资格。
	GetTaskDraftCollection(ctx context.Context, in *GetTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftCollectionResponse, error)
	// 显式指定稳定项序号；缺序号不默认第0项。
	GetTaskDraftItem(ctx context.Context, in *GetTaskDraftItemRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error)
	// 本人编辑指定项文字；版本只保护该项，缺项身份/版本拒绝。
	EditTaskDraftItemText(ctx context.Context, in *EditTaskDraftItemTextRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error)
	// 本人明确选择该项负责人；正ID仍由User核对当前成员资格。
	SelectTaskDraftItemAssignee(ctx context.Context, in *SelectTaskDraftItemAssigneeRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error)
	// 本人设置/清除该项截止时间；保留原始解释依据。
	EditTaskDraftItemDeadline(ctx context.Context, in *EditTaskDraftItemDeadlineRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error)
	// 本人逐项审查并创建；先持久冻结，再以固定项请求键调用 Task。
	ConfirmTaskDraftItem(ctx context.Context, in *ConfirmTaskDraftItemRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error)
	// 本人显式跳过未提交项，保留原内容；冻结或成功项不能跳过。
	SkipTaskDraftItem(ctx context.Context, in *SkipTaskDraftItemRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskResponse)
	err := c.cc.Invoke(ctx, Agent_Ask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetTaskDraft(ctx context.Context, in *GetTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_GetTaskDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PrepareTaskDraft(ctx context.Context, in *PrepareTaskDraftRequest, opts ...grpc.CallOption) (*PrepareTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_PrepareTaskDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) EditTaskDraft(ctx context.Context, in *EditTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_EditTaskDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SelectTaskDraftAssignee(ctx context.Context, in *SelectTaskDraftAssigneeRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_SelectTaskDraftAssignee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) EditTaskDraftDeadline(ctx context.Context, in *EditTaskDraftDeadlineRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_EditTaskDraftDeadline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ConfirmTaskDraft(ctx context.Context, in *ConfirmTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_ConfirmTaskDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RetryTaskReply(ctx context.Context, in *GetTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_RetryTaskReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PrepareTaskDraftCollection(ctx context.Context, in *PrepareTaskDraftRequest, opts ...grpc.CallOption) (*PrepareTaskDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareTaskDraftResponse)
	err := c.cc.Invoke(ctx, Agent_PrepareTaskDraftCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetTaskDraftCollection(ctx context.Context, in *GetTaskDraftRequest, opts ...grpc.CallOption) (*GetTaskDraftCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftCollectionResponse)
	err := c.cc.Invoke(ctx, Agent_GetTaskDraftCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetTaskDraftItem(ctx context.Context, in *GetTaskDraftItemRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftItemResponse)
	err := c.cc.Invoke(ctx, Agent_GetTaskDraftItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) EditTaskDraftItemText(ctx context.Context, in *EditTaskDraftItemTextRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftItemResponse)
	err := c.cc.Invoke(ctx, Agent_EditTaskDraftItemText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SelectTaskDraftItemAssignee(ctx context.Context, in *SelectTaskDraftItemAssigneeRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftItemResponse)
	err := c.cc.Invoke(ctx, Agent_SelectTaskDraftItemAssignee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) EditTaskDraftItemDeadline(ctx context.Context, in *EditTaskDraftItemDeadlineRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftItemResponse)
	err := c.cc.Invoke(ctx, Agent_EditTaskDraftItemDeadline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ConfirmTaskDraftItem(ctx context.Context, in *ConfirmTaskDraftItemRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftItemResponse)
	err := c.cc.Invoke(ctx, Agent_ConfirmTaskDraftItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SkipTaskDraftItem(ctx context.Context, in *SkipTaskDraftItemRequest, opts ...grpc.CallOption) (*GetTaskDraftItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDraftItemResponse)
	err := c.cc.Invoke(ctx, Agent_SkipTaskDraftItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
type AgentServer interface {
	// authorization: Bearer <token> 经 gRPC metadata 传入；第一版只读问答。
	Ask(context.Context, *AskRequest) (*AskResponse, error)
	// 仅草稿发起人可读取；每次读取都重新校验当前团队群资格。
	GetTaskDraft(context.Context, *GetTaskDraftRequest) (*GetTaskDraftResponse, error)
	// 显式生成一项待确认草稿；authorization 与 idempotency-key 经 metadata 传入。
	PrepareTaskDraft(context.Context, *PrepareTaskDraftRequest) (*PrepareTaskDraftResponse, error)
	// 仅发起人可修改待确认草稿的标题和说明；每次重新校验当前团队群资格。
	EditTaskDraft(context.Context, *EditTaskDraftRequest) (*GetTaskDraftResponse, error)
	// 本人明确选择当前团队成员或未指派；必须携带读取的内容版本。
	SelectTaskDraftAssignee(context.Context, *SelectTaskDraftAssigneeRequest) (*GetTaskDraftResponse, error)
	// 本人编辑已保存草稿截止时间；0 明确清除，缺字段拒绝，冻结后不可改。
	EditTaskDraftDeadline(context.Context, *EditTaskDraftDeadlineRequest) (*GetTaskDraftResponse, error)
	// 仅发起人可确认；冻结内容及服务端请求键，重复请求复用原任务。
	ConfirmTaskDraft(context.Context, *ConfirmTaskDraftRequest) (*GetTaskDraftResponse, error)
	// 仅本人显式重试原回帖；不重新创建任务，不接受任意正文或群范围。
	RetryTaskReply(context.Context, *GetTaskDraftRequest) (*GetTaskDraftResponse, error)
	// 一次生成并原子保存1..5项候选；和旧单项生成区分请求意图。
	PrepareTaskDraftCollection(context.Context, *PrepareTaskDraftRequest) (*PrepareTaskDraftResponse, error)
	// 仅发起人可读完整集合，每次重新核对当前团队群资格。
	GetTaskDraftCollection(context.Context, *GetTaskDraftRequest) (*GetTaskDraftCollectionResponse, error)
	// 显式指定稳定项序号；缺序号不默认第0项。
	GetTaskDraftItem(context.Context, *GetTaskDraftItemRequest) (*GetTaskDraftItemResponse, error)
	// 本人编辑指定项文字；版本只保护该项，缺项身份/版本拒绝。
	EditTaskDraftItemText(context.Context, *EditTaskDraftItemTextRequest) (*GetTaskDraftItemResponse, error)
	// 本人明确选择该项负责人；正ID仍由User核对当前成员资格。
	SelectTaskDraftItemAssignee(context.Context, *SelectTaskDraftItemAssigneeRequest) (*GetTaskDraftItemResponse, error)
	// 本人设置/清除该项截止时间；保留原始解释依据。
	EditTaskDraftItemDeadline(context.Context, *EditTaskDraftItemDeadlineRequest) (*GetTaskDraftItemResponse, error)
	// 本人逐项审查并创建；先持久冻结，再以固定项请求键调用 Task。
	ConfirmTaskDraftItem(context.Context, *ConfirmTaskDraftItemRequest) (*GetTaskDraftItemResponse, error)
	// 本人显式跳过未提交项，保留原内容；冻结或成功项不能跳过。
	SkipTaskDraftItem(context.Context, *SkipTaskDraftItemRequest) (*GetTaskDraftItemResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) Ask(context.Context, *AskRequest) (*AskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedAgentServer) GetTaskDraft(context.Context, *GetTaskDraftRequest) (*GetTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskDraft not implemented")
}
func (UnimplementedAgentServer) PrepareTaskDraft(context.Context, *PrepareTaskDraftRequest) (*PrepareTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareTaskDraft not implemented")
}
func (UnimplementedAgentServer) EditTaskDraft(context.Context, *EditTaskDraftRequest) (*GetTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTaskDraft not implemented")
}
func (UnimplementedAgentServer) SelectTaskDraftAssignee(context.Context, *SelectTaskDraftAssigneeRequest) (*GetTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectTaskDraftAssignee not implemented")
}
func (UnimplementedAgentServer) EditTaskDraftDeadline(context.Context, *EditTaskDraftDeadlineRequest) (*GetTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTaskDraftDeadline not implemented")
}
func (UnimplementedAgentServer) ConfirmTaskDraft(context.Context, *ConfirmTaskDraftRequest) (*GetTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTaskDraft not implemented")
}
func (UnimplementedAgentServer) RetryTaskReply(context.Context, *GetTaskDraftRequest) (*GetTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryTaskReply not implemented")
}
func (UnimplementedAgentServer) PrepareTaskDraftCollection(context.Context, *PrepareTaskDraftRequest) (*PrepareTaskDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareTaskDraftCollection not implemented")
}
func (UnimplementedAgentServer) GetTaskDraftCollection(context.Context, *GetTaskDraftRequest) (*GetTaskDraftCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskDraftCollection not implemented")
}
func (UnimplementedAgentServer) GetTaskDraftItem(context.Context, *GetTaskDraftItemRequest) (*GetTaskDraftItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskDraftItem not implemented")
}
func (UnimplementedAgentServer) EditTaskDraftItemText(context.Context, *EditTaskDraftItemTextRequest) (*GetTaskDraftItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTaskDraftItemText not implemented")
}
func (UnimplementedAgentServer) SelectTaskDraftItemAssignee(context.Context, *SelectTaskDraftItemAssigneeRequest) (*GetTaskDraftItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectTaskDraftItemAssignee not implemented")
}
func (UnimplementedAgentServer) EditTaskDraftItemDeadline(context.Context, *EditTaskDraftItemDeadlineRequest) (*GetTaskDraftItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTaskDraftItemDeadline not implemented")
}
func (UnimplementedAgentServer) ConfirmTaskDraftItem(context.Context, *ConfirmTaskDraftItemRequest) (*GetTaskDraftItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTaskDraftItem not implemented")
}
func (UnimplementedAgentServer) SkipTaskDraftItem(context.Context, *SkipTaskDraftItemRequest) (*GetTaskDraftItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SkipTaskDraftItem not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call pancis, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Ask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Ask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Ask(ctx, req.(*AskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetTaskDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetTaskDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetTaskDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetTaskDraft(ctx, req.(*GetTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PrepareTaskDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PrepareTaskDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PrepareTaskDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PrepareTaskDraft(ctx, req.(*PrepareTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_EditTaskDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).EditTaskDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_EditTaskDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).EditTaskDraft(ctx, req.(*EditTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SelectTaskDraftAssignee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectTaskDraftAssigneeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SelectTaskDraftAssignee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_SelectTaskDraftAssignee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SelectTaskDraftAssignee(ctx, req.(*SelectTaskDraftAssigneeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_EditTaskDraftDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTaskDraftDeadlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).EditTaskDraftDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_EditTaskDraftDeadline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).EditTaskDraftDeadline(ctx, req.(*EditTaskDraftDeadlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ConfirmTaskDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ConfirmTaskDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ConfirmTaskDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ConfirmTaskDraft(ctx, req.(*ConfirmTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RetryTaskReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RetryTaskReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RetryTaskReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RetryTaskReply(ctx, req.(*GetTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PrepareTaskDraftCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PrepareTaskDraftCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PrepareTaskDraftCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PrepareTaskDraftCollection(ctx, req.(*PrepareTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetTaskDraftCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetTaskDraftCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetTaskDraftCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetTaskDraftCollection(ctx, req.(*GetTaskDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetTaskDraftItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskDraftItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetTaskDraftItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetTaskDraftItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetTaskDraftItem(ctx, req.(*GetTaskDraftItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_EditTaskDraftItemText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTaskDraftItemTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).EditTaskDraftItemText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_EditTaskDraftItemText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).EditTaskDraftItemText(ctx, req.(*EditTaskDraftItemTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SelectTaskDraftItemAssignee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectTaskDraftItemAssigneeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SelectTaskDraftItemAssignee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_SelectTaskDraftItemAssignee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SelectTaskDraftItemAssignee(ctx, req.(*SelectTaskDraftItemAssigneeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_EditTaskDraftItemDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTaskDraftItemDeadlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).EditTaskDraftItemDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_EditTaskDraftItemDeadline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).EditTaskDraftItemDeadline(ctx, req.(*EditTaskDraftItemDeadlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ConfirmTaskDraftItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTaskDraftItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ConfirmTaskDraftItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ConfirmTaskDraftItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ConfirmTaskDraftItem(ctx, req.(*ConfirmTaskDraftItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SkipTaskDraftItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkipTaskDraftItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SkipTaskDraftItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_SkipTaskDraftItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SkipTaskDraftItem(ctx, req.(*SkipTaskDraftItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ask",
			Handler:    _Agent_Ask_Handler,
		},
		{
			MethodName: "GetTaskDraft",
			Handler:    _Agent_GetTaskDraft_Handler,
		},
		{
			MethodName: "PrepareTaskDraft",
			Handler:    _Agent_PrepareTaskDraft_Handler,
		},
		{
			MethodName: "EditTaskDraft",
			Handler:    _Agent_EditTaskDraft_Handler,
		},
		{
			MethodName: "SelectTaskDraftAssignee",
			Handler:    _Agent_SelectTaskDraftAssignee_Handler,
		},
		{
			MethodName: "EditTaskDraftDeadline",
			Handler:    _Agent_EditTaskDraftDeadline_Handler,
		},
		{
			MethodName: "ConfirmTaskDraft",
			Handler:    _Agent_ConfirmTaskDraft_Handler,
		},
		{
			MethodName: "RetryTaskReply",
			Handler:    _Agent_RetryTaskReply_Handler,
		},
		{
			MethodName: "PrepareTaskDraftCollection",
			Handler:    _Agent_PrepareTaskDraftCollection_Handler,
		},
		{
			MethodName: "GetTaskDraftCollection",
			Handler:    _Agent_GetTaskDraftCollection_Handler,
		},
		{
			MethodName: "GetTaskDraftItem",
			Handler:    _Agent_GetTaskDraftItem_Handler,
		},
		{
			MethodName: "EditTaskDraftItemText",
			Handler:    _Agent_EditTaskDraftItemText_Handler,
		},
		{
			MethodName: "SelectTaskDraftItemAssignee",
			Handler:    _Agent_SelectTaskDraftItemAssignee_Handler,
		},
		{
			MethodName: "EditTaskDraftItemDeadline",
			Handler:    _Agent_EditTaskDraftItemDeadline_Handler,
		},
		{
			MethodName: "ConfirmTaskDraftItem",
			Handler:    _Agent_ConfirmTaskDraftItem_Handler,
		},
		{
			MethodName: "SkipTaskDraftItem",
			Handler:    _Agent_SkipTaskDraftItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
