// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: push.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserPush_CheckPushTeamMember_FullMethodName = "/user.UserPush/CheckPushTeamMember"
)

// UserPushClient is the client API for UserPush service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dedicated Push-only mTLS service. Never register it on ordinary User or
// IM-trigger listeners; this method does not authorize access to a group.
type UserPushClient interface {
	CheckPushTeamMember(ctx context.Context, in *CheckPushTeamMemberRequest, opts ...grpc.CallOption) (*CheckPushTeamMemberResponse, error)
}

type userPushClient struct {
	cc grpc.ClientConnInterface
}

func NewUserPushClient(cc grpc.ClientConnInterface) UserPushClient {
	return &userPushClient{cc}
}

func (c *userPushClient) CheckPushTeamMember(ctx context.Context, in *CheckPushTeamMemberRequest, opts ...grpc.CallOption) (*CheckPushTeamMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPushTeamMemberResponse)
	err := c.cc.Invoke(ctx, UserPush_CheckPushTeamMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserPushServer is the server API for UserPush service.
// All implementations must embed UnimplementedUserPushServer
// for forward compatibility.
//
// Dedicated Push-only mTLS service. Never register it on ordinary User or
// IM-trigger listeners; this method does not authorize access to a group.
type UserPushServer interface {
	CheckPushTeamMember(context.Context, *CheckPushTeamMemberRequest) (*CheckPushTeamMemberResponse, error)
	mustEmbedUnimplementedUserPushServer()
}

// UnimplementedUserPushServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserPushServer struct{}

func (UnimplementedUserPushServer) CheckPushTeamMember(context.Context, *CheckPushTeamMemberRequest) (*CheckPushTeamMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPushTeamMember not implemented")
}
func (UnimplementedUserPushServer) mustEmbedUnimplementedUserPushServer() {}
func (UnimplementedUserPushServer) testEmbeddedByValue()                  {}

// UnsafeUserPushServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserPushServer will
// result in compilation errors.
type UnsafeUserPushServer interface {
	mustEmbedUnimplementedUserPushServer()
}

func RegisterUserPushServer(s grpc.ServiceRegistrar, srv UserPushServer) {
	// If the following call pancis, it indicates UnimplementedUserPushServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserPush_ServiceDesc, srv)
}

func _UserPush_CheckPushTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPushTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserPushServer).CheckPushTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserPush_CheckPushTeamMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserPushServer).CheckPushTeamMember(ctx, req.(*CheckPushTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserPush_ServiceDesc is the grpc.ServiceDesc for UserPush service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserPush_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserPush",
	HandlerType: (*UserPushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPushTeamMember",
			Handler:    _UserPush_CheckPushTeamMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push.proto",
}
