// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: rpc/user/trigger.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckTriggerTeamMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IM derives both IDs from its persisted trigger, not Kafka or user metadata.
	ActorId       int64 `protobuf:"varint,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	TeamId        int64 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTriggerTeamMemberRequest) Reset() {
	*x = CheckTriggerTeamMemberRequest{}
	mi := &file_rpc_user_trigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTriggerTeamMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTriggerTeamMemberRequest) ProtoMessage() {}

func (x *CheckTriggerTeamMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_trigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTriggerTeamMemberRequest.ProtoReflect.Descriptor instead.
func (*CheckTriggerTeamMemberRequest) Descriptor() ([]byte, []int) {
	return file_rpc_user_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *CheckTriggerTeamMemberRequest) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *CheckTriggerTeamMemberRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type CheckTriggerTeamMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echo only the checked scope. An empty or different result is not success.
	ActorId       int64 `protobuf:"varint,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	TeamId        int64 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTriggerTeamMemberResponse) Reset() {
	*x = CheckTriggerTeamMemberResponse{}
	mi := &file_rpc_user_trigger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTriggerTeamMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTriggerTeamMemberResponse) ProtoMessage() {}

func (x *CheckTriggerTeamMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_trigger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTriggerTeamMemberResponse.ProtoReflect.Descriptor instead.
func (*CheckTriggerTeamMemberResponse) Descriptor() ([]byte, []int) {
	return file_rpc_user_trigger_proto_rawDescGZIP(), []int{1}
}

func (x *CheckTriggerTeamMemberResponse) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *CheckTriggerTeamMemberResponse) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

var File_rpc_user_trigger_proto protoreflect.FileDescriptor

const file_rpc_user_trigger_proto_rawDesc = "" +
	"\n" +
	"\x16rpc/user/trigger.proto\x12\x04user\"S\n" +
	"\x1dCheckTriggerTeamMemberRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\x03R\aactorId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\"T\n" +
	"\x1eCheckTriggerTeamMemberResponse\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\x03R\aactorId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId2r\n" +
	"\vUserTrigger\x12c\n" +
	"\x16CheckTriggerTeamMember\x12#.user.CheckTriggerTeamMemberRequest\x1a$.user.CheckTriggerTeamMemberResponseB&Z$github.com/yjydist/go-im/rpc/user/pbb\x06proto3"

var (
	file_rpc_user_trigger_proto_rawDescOnce sync.Once
	file_rpc_user_trigger_proto_rawDescData []byte
)

func file_rpc_user_trigger_proto_rawDescGZIP() []byte {
	file_rpc_user_trigger_proto_rawDescOnce.Do(func() {
		file_rpc_user_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_user_trigger_proto_rawDesc), len(file_rpc_user_trigger_proto_rawDesc)))
	})
	return file_rpc_user_trigger_proto_rawDescData
}

var file_rpc_user_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_user_trigger_proto_goTypes = []any{
	(*CheckTriggerTeamMemberRequest)(nil),  // 0: user.CheckTriggerTeamMemberRequest
	(*CheckTriggerTeamMemberResponse)(nil), // 1: user.CheckTriggerTeamMemberResponse
}
var file_rpc_user_trigger_proto_depIdxs = []int32{
	0, // 0: user.UserTrigger.CheckTriggerTeamMember:input_type -> user.CheckTriggerTeamMemberRequest
	1, // 1: user.UserTrigger.CheckTriggerTeamMember:output_type -> user.CheckTriggerTeamMemberResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_user_trigger_proto_init() }
func file_rpc_user_trigger_proto_init() {
	if File_rpc_user_trigger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_user_trigger_proto_rawDesc), len(file_rpc_user_trigger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_user_trigger_proto_goTypes,
		DependencyIndexes: file_rpc_user_trigger_proto_depIdxs,
		MessageInfos:      file_rpc_user_trigger_proto_msgTypes,
	}.Build()
	File_rpc_user_trigger_proto = out.File
	file_rpc_user_trigger_proto_goTypes = nil
	file_rpc_user_trigger_proto_depIdxs = nil
}
