// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: rpc/user/trigger.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserTrigger_CheckTriggerTeamMember_FullMethodName = "/user.UserTrigger/CheckTriggerTeamMember"
)

// UserTriggerClient is the client API for UserTrigger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Only on User's dedicated mTLS port, allowing the exact trusted IM service.
// Never grants a user login or exposes profile/password/role information.
type UserTriggerClient interface {
	CheckTriggerTeamMember(ctx context.Context, in *CheckTriggerTeamMemberRequest, opts ...grpc.CallOption) (*CheckTriggerTeamMemberResponse, error)
}

type userTriggerClient struct {
	cc grpc.ClientConnInterface
}

func NewUserTriggerClient(cc grpc.ClientConnInterface) UserTriggerClient {
	return &userTriggerClient{cc}
}

func (c *userTriggerClient) CheckTriggerTeamMember(ctx context.Context, in *CheckTriggerTeamMemberRequest, opts ...grpc.CallOption) (*CheckTriggerTeamMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTriggerTeamMemberResponse)
	err := c.cc.Invoke(ctx, UserTrigger_CheckTriggerTeamMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserTriggerServer is the server API for UserTrigger service.
// All implementations must embed UnimplementedUserTriggerServer
// for forward compatibility.
//
// Only on User's dedicated mTLS port, allowing the exact trusted IM service.
// Never grants a user login or exposes profile/password/role information.
type UserTriggerServer interface {
	CheckTriggerTeamMember(context.Context, *CheckTriggerTeamMemberRequest) (*CheckTriggerTeamMemberResponse, error)
	mustEmbedUnimplementedUserTriggerServer()
}

// UnimplementedUserTriggerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserTriggerServer struct{}

func (UnimplementedUserTriggerServer) CheckTriggerTeamMember(context.Context, *CheckTriggerTeamMemberRequest) (*CheckTriggerTeamMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTriggerTeamMember not implemented")
}
func (UnimplementedUserTriggerServer) mustEmbedUnimplementedUserTriggerServer() {}
func (UnimplementedUserTriggerServer) testEmbeddedByValue()                     {}

// UnsafeUserTriggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserTriggerServer will
// result in compilation errors.
type UnsafeUserTriggerServer interface {
	mustEmbedUnimplementedUserTriggerServer()
}

func RegisterUserTriggerServer(s grpc.ServiceRegistrar, srv UserTriggerServer) {
	// If the following call pancis, it indicates UnimplementedUserTriggerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserTrigger_ServiceDesc, srv)
}

func _UserTrigger_CheckTriggerTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTriggerTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserTriggerServer).CheckTriggerTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserTrigger_CheckTriggerTeamMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserTriggerServer).CheckTriggerTeamMember(ctx, req.(*CheckTriggerTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserTrigger_ServiceDesc is the grpc.ServiceDesc for UserTrigger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserTrigger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserTrigger",
	HandlerType: (*UserTriggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTriggerTeamMember",
			Handler:    _UserTrigger_CheckTriggerTeamMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/user/trigger.proto",
}
