// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListMyTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterTeamId   int64                  `protobuf:"varint,1,opt,name=after_team_id,json=afterTeamId,proto3" json:"after_team_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyTeamsRequest) Reset() {
	*x = ListMyTeamsRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyTeamsRequest) ProtoMessage() {}

func (x *ListMyTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyTeamsRequest.ProtoReflect.Descriptor instead.
func (*ListMyTeamsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *ListMyTeamsRequest) GetAfterTeamId() int64 {
	if x != nil {
		return x.AfterTeamId
	}
	return 0
}

func (x *ListMyTeamsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MyTeam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyTeam) Reset() {
	*x = MyTeam{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyTeam) ProtoMessage() {}

func (x *MyTeam) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyTeam.ProtoReflect.Descriptor instead.
func (*MyTeam) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *MyTeam) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *MyTeam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MyTeam) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type ListMyTeamsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Teams           []*MyTeam              `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	NextAfterTeamId int64                  `protobuf:"varint,2,opt,name=next_after_team_id,json=nextAfterTeamId,proto3" json:"next_after_team_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMyTeamsResponse) Reset() {
	*x = ListMyTeamsResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyTeamsResponse) ProtoMessage() {}

func (x *ListMyTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListMyTeamsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListMyTeamsResponse) GetTeams() []*MyTeam {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *ListMyTeamsResponse) GetNextAfterTeamId() int64 {
	if x != nil {
		return x.NextAfterTeamId
	}
	return 0
}

type BatchGetConversationDisplayNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // 最多 100 个正 ID。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetConversationDisplayNamesRequest) Reset() {
	*x = BatchGetConversationDisplayNamesRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetConversationDisplayNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetConversationDisplayNamesRequest) ProtoMessage() {}

func (x *BatchGetConversationDisplayNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetConversationDisplayNamesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetConversationDisplayNamesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetConversationDisplayNamesRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type ConversationDisplayName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // 昵称优先、用户名兜底；无可用资料时不返回该 ID。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationDisplayName) Reset() {
	*x = ConversationDisplayName{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationDisplayName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationDisplayName) ProtoMessage() {}

func (x *ConversationDisplayName) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationDisplayName.ProtoReflect.Descriptor instead.
func (*ConversationDisplayName) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *ConversationDisplayName) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConversationDisplayName) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type BatchGetConversationDisplayNamesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Users         []*ConversationDisplayName `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetConversationDisplayNamesResponse) Reset() {
	*x = BatchGetConversationDisplayNamesResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetConversationDisplayNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetConversationDisplayNamesResponse) ProtoMessage() {}

func (x *BatchGetConversationDisplayNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetConversationDisplayNamesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetConversationDisplayNamesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetConversationDisplayNamesResponse) GetUsers() []*ConversationDisplayName {
	if x != nil {
		return x.Users
	}
	return nil
}

type LeaveTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RequestKey    string                 `protobuf:"bytes,2,opt,name=request_key,json=requestKey,proto3" json:"request_key,omitempty"` // 1—64 位 ASCII 字母、数字、- 或 _。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveTeamRequest) Reset() {
	*x = LeaveTeamRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveTeamRequest) ProtoMessage() {}

func (x *LeaveTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveTeamRequest.ProtoReflect.Descriptor instead.
func (*LeaveTeamRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveTeamRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *LeaveTeamRequest) GetRequestKey() string {
	if x != nil {
		return x.RequestKey
	}
	return ""
}

type GetTeamLeaveOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RequestKey    string                 `protobuf:"bytes,2,opt,name=request_key,json=requestKey,proto3" json:"request_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamLeaveOperationRequest) Reset() {
	*x = GetTeamLeaveOperationRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamLeaveOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamLeaveOperationRequest) ProtoMessage() {}

func (x *GetTeamLeaveOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamLeaveOperationRequest.ProtoReflect.Descriptor instead.
func (*GetTeamLeaveOperationRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetTeamLeaveOperationRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GetTeamLeaveOperationRequest) GetRequestKey() string {
	if x != nil {
		return x.RequestKey
	}
	return ""
}

type TeamLeaveOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   int64                  `protobuf:"varint,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	TeamId        int64                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Generation    int64                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"` // 0：待清理（可同键重试）；1：已完成。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamLeaveOperationResponse) Reset() {
	*x = TeamLeaveOperationResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamLeaveOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamLeaveOperationResponse) ProtoMessage() {}

func (x *TeamLeaveOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamLeaveOperationResponse.ProtoReflect.Descriptor instead.
func (*TeamLeaveOperationResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *TeamLeaveOperationResponse) GetOperationId() int64 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *TeamLeaveOperationResponse) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *TeamLeaveOperationResponse) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *TeamLeaveOperationResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ResolveTeamMemberRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TeamId int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// 去除输入首尾空白后匹配，1—64 个 Unicode 字符；区分大小写与重音。
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTeamMemberRequest) Reset() {
	*x = ResolveTeamMemberRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTeamMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTeamMemberRequest) ProtoMessage() {}

func (x *ResolveTeamMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTeamMemberRequest.ProtoReflect.Descriptor instead.
func (*ResolveTeamMemberRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveTeamMemberRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ResolveTeamMemberRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResolveTeamMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 按用户 ID 升序，最多 20 个。同一成员匹配两个字段也只出现一次。
	Candidates []*TeamMember `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// 还有未返回的匹配成员；仅候选数为 1 且本字段为 false 才能判断唯一。
	Truncated     bool `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTeamMemberResponse) Reset() {
	*x = ResolveTeamMemberResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTeamMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTeamMemberResponse) ProtoMessage() {}

func (x *ResolveTeamMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTeamMemberResponse.ProtoReflect.Descriptor instead.
func (*ResolveTeamMemberResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveTeamMemberResponse) GetCandidates() []*TeamMember {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ResolveTeamMemberResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type CheckTeamMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamMemberRequest) Reset() {
	*x = CheckTeamMemberRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamMemberRequest) ProtoMessage() {}

func (x *CheckTeamMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamMemberRequest.ProtoReflect.Descriptor instead.
func (*CheckTeamMemberRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *CheckTeamMemberRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type CheckTeamMemberResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role   int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"` // 0 普通成员、1 管理员、2 拥有者。
	// 当前活动资格版本；跨服务退出/重入时不可重置，非正数不能用于版本授权。
	Generation    int64 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamMemberResponse) Reset() {
	*x = CheckTeamMemberResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamMemberResponse) ProtoMessage() {}

func (x *CheckTeamMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamMemberResponse.ProtoReflect.Descriptor instead.
func (*CheckTeamMemberResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *CheckTeamMemberResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckTeamMemberResponse) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *CheckTeamMemberResponse) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type CheckTeamMemberByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamMemberByIDRequest) Reset() {
	*x = CheckTeamMemberByIDRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamMemberByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamMemberByIDRequest) ProtoMessage() {}

func (x *CheckTeamMemberByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamMemberByIDRequest.ProtoReflect.Descriptor instead.
func (*CheckTeamMemberByIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *CheckTeamMemberByIDRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CheckTeamMemberByIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckTeamMemberByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeamMemberByIDResponse) Reset() {
	*x = CheckTeamMemberByIDResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeamMemberByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamMemberByIDResponse) ProtoMessage() {}

func (x *CheckTeamMemberByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamMemberByIDResponse.ProtoReflect.Descriptor instead.
func (*CheckTeamMemberByIDResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

type AuthorizeTeamGroupCreationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeTeamGroupCreationRequest) Reset() {
	*x = AuthorizeTeamGroupCreationRequest{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeTeamGroupCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeTeamGroupCreationRequest) ProtoMessage() {}

func (x *AuthorizeTeamGroupCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeTeamGroupCreationRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeTeamGroupCreationRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *AuthorizeTeamGroupCreationRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type AuthorizeTeamGroupCreationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Generation    int64                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeTeamGroupCreationResponse) Reset() {
	*x = AuthorizeTeamGroupCreationResponse{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeTeamGroupCreationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeTeamGroupCreationResponse) ProtoMessage() {}

func (x *AuthorizeTeamGroupCreationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeTeamGroupCreationResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeTeamGroupCreationResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *AuthorizeTeamGroupCreationResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthorizeTeamGroupCreationResponse) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type SetTeamMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"` // 只允许 0 普通成员或 1 管理员。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTeamMemberRoleRequest) Reset() {
	*x = SetTeamMemberRoleRequest{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTeamMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTeamMemberRoleRequest) ProtoMessage() {}

func (x *SetTeamMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTeamMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*SetTeamMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *SetTeamMemberRoleRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *SetTeamMemberRoleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetTeamMemberRoleRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type SetTeamMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTeamMemberRoleResponse) Reset() {
	*x = SetTeamMemberRoleResponse{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTeamMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTeamMemberRoleResponse) ProtoMessage() {}

func (x *SetTeamMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTeamMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*SetTeamMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

type ListTeamMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	AfterUserId   int64                  `protobuf:"varint,2,opt,name=after_user_id,json=afterUserId,proto3" json:"after_user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamMembersRequest) Reset() {
	*x = ListTeamMembersRequest{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamMembersRequest) ProtoMessage() {}

func (x *ListTeamMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamMembersRequest.ProtoReflect.Descriptor instead.
func (*ListTeamMembersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *ListTeamMembersRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ListTeamMembersRequest) GetAfterUserId() int64 {
	if x != nil {
		return x.AfterUserId
	}
	return 0
}

func (x *ListTeamMembersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TeamMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamMember) Reset() {
	*x = TeamMember{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMember) ProtoMessage() {}

func (x *TeamMember) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMember.ProtoReflect.Descriptor instead.
func (*TeamMember) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *TeamMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TeamMember) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TeamMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *TeamMember) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type ListTeamMembersResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Members         []*TeamMember          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	NextAfterUserId int64                  `protobuf:"varint,2,opt,name=next_after_user_id,json=nextAfterUserId,proto3" json:"next_after_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListTeamMembersResponse) Reset() {
	*x = ListTeamMembersResponse{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamMembersResponse) ProtoMessage() {}

func (x *ListTeamMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamMembersResponse.ProtoReflect.Descriptor instead.
func (*ListTeamMembersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *ListTeamMembersResponse) GetMembers() []*TeamMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListTeamMembersResponse) GetNextAfterUserId() int64 {
	if x != nil {
		return x.NextAfterUserId
	}
	return 0
}

type AddTeamMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamMemberRequest) Reset() {
	*x = AddTeamMemberRequest{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamMemberRequest) ProtoMessage() {}

func (x *AddTeamMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamMemberRequest.ProtoReflect.Descriptor instead.
func (*AddTeamMemberRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *AddTeamMemberRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *AddTeamMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddTeamMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamMemberResponse) Reset() {
	*x = AddTeamMemberResponse{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamMemberResponse) ProtoMessage() {}

func (x *AddTeamMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamMemberResponse.ProtoReflect.Descriptor instead.
func (*AddTeamMemberResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

type CreateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *CreateTeamResponse) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type GetMyInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyInfoRequest) Reset() {
	*x = GetMyInfoRequest{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInfoRequest) ProtoMessage() {}

func (x *GetMyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMyInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{28}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{29}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{30}
}

type GetUserInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 演示用户 ID 固定为 1；此字段不构成用户身份证明。
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{31}
}

func (x *GetUserInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{32}
}

func (x *GetUserInfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserInfoResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserInfoResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"N\n" +
	"\x12ListMyTeamsRequest\x12\"\n" +
	"\rafter_team_id\x18\x01 \x01(\x03R\vafterTeamId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"I\n" +
	"\x06MyTeam\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\"f\n" +
	"\x13ListMyTeamsResponse\x12\"\n" +
	"\x05teams\x18\x01 \x03(\v2\f.user.MyTeamR\x05teams\x12+\n" +
	"\x12next_after_team_id\x18\x02 \x01(\x03R\x0fnextAfterTeamId\"D\n" +
	"'BatchGetConversationDisplayNamesRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"U\n" +
	"\x17ConversationDisplayName\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"_\n" +
	"(BatchGetConversationDisplayNamesResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.user.ConversationDisplayNameR\x05users\"L\n" +
	"\x10LeaveTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x1f\n" +
	"\vrequest_key\x18\x02 \x01(\tR\n" +
	"requestKey\"X\n" +
	"\x1cGetTeamLeaveOperationRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x1f\n" +
	"\vrequest_key\x18\x02 \x01(\tR\n" +
	"requestKey\"\x90\x01\n" +
	"\x1aTeamLeaveOperationResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\x03R\voperationId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x03R\n" +
	"generation\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"G\n" +
	"\x18ResolveTeamMemberRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"k\n" +
	"\x19ResolveTeamMemberResponse\x120\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x10.user.TeamMemberR\n" +
	"candidates\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\"1\n" +
	"\x16CheckTeamMemberRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\"f\n" +
	"\x17CheckTeamMemberResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x03R\n" +
	"generation\"N\n" +
	"\x1aCheckTeamMemberByIDRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x1d\n" +
	"\x1bCheckTeamMemberByIDResponse\"<\n" +
	"!AuthorizeTeamGroupCreationRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\"]\n" +
	"\"AuthorizeTeamGroupCreationResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x03R\n" +
	"generation\"`\n" +
	"\x18SetTeamMemberRoleRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\"\x1b\n" +
	"\x19SetTeamMemberRoleResponse\"k\n" +
	"\x16ListTeamMembersRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\"\n" +
	"\rafter_user_id\x18\x02 \x01(\x03R\vafterUserId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"q\n" +
	"\n" +
	"TeamMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\"r\n" +
	"\x17ListTeamMembersResponse\x12*\n" +
	"\amembers\x18\x01 \x03(\v2\x10.user.TeamMemberR\amembers\x12+\n" +
	"\x12next_after_user_id\x18\x02 \x01(\x03R\x0fnextAfterUserId\"H\n" +
	"\x14AddTeamMemberRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x17\n" +
	"\x15AddTeamMemberResponse\"'\n" +
	"\x11CreateTeamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"-\n" +
	"\x12CreateTeamResponse\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\"\x12\n" +
	"\x10GetMyInfoRequest\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"e\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"\x12\n" +
	"\x10RegisterResponse\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"]\n" +
	"\x13GetUserInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname2\x89\n" +
	"\n" +
	"\x04User\x12B\n" +
	"\vGetUserInfo\x12\x18.user.GetUserInfoRequest\x1a\x19.user.GetUserInfoResponse\x12>\n" +
	"\tGetMyInfo\x12\x16.user.GetMyInfoRequest\x1a\x19.user.GetUserInfoResponse\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x129\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x12?\n" +
	"\n" +
	"CreateTeam\x12\x17.user.CreateTeamRequest\x1a\x18.user.CreateTeamResponse\x12H\n" +
	"\rAddTeamMember\x12\x1a.user.AddTeamMemberRequest\x1a\x1b.user.AddTeamMemberResponse\x12N\n" +
	"\x0fListTeamMembers\x12\x1c.user.ListTeamMembersRequest\x1a\x1d.user.ListTeamMembersResponse\x12T\n" +
	"\x11SetTeamMemberRole\x12\x1e.user.SetTeamMemberRoleRequest\x1a\x1f.user.SetTeamMemberRoleResponse\x12o\n" +
	"\x1aAuthorizeTeamGroupCreation\x12'.user.AuthorizeTeamGroupCreationRequest\x1a(.user.AuthorizeTeamGroupCreationResponse\x12N\n" +
	"\x0fCheckTeamMember\x12\x1c.user.CheckTeamMemberRequest\x1a\x1d.user.CheckTeamMemberResponse\x12Z\n" +
	"\x13CheckTeamMemberByID\x12 .user.CheckTeamMemberByIDRequest\x1a!.user.CheckTeamMemberByIDResponse\x12T\n" +
	"\x11ResolveTeamMember\x12\x1e.user.ResolveTeamMemberRequest\x1a\x1f.user.ResolveTeamMemberResponse\x12E\n" +
	"\tLeaveTeam\x12\x16.user.LeaveTeamRequest\x1a .user.TeamLeaveOperationResponse\x12]\n" +
	"\x15GetTeamLeaveOperation\x12\".user.GetTeamLeaveOperationRequest\x1a .user.TeamLeaveOperationResponse\x12B\n" +
	"\vListMyTeams\x12\x18.user.ListMyTeamsRequest\x1a\x19.user.ListMyTeamsResponse\x12\x81\x01\n" +
	" BatchGetConversationDisplayNames\x12-.user.BatchGetConversationDisplayNamesRequest\x1a..user.BatchGetConversationDisplayNamesResponseB&Z$github.com/yjydist/go-im/rpc/user/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_user_proto_goTypes = []any{
	(*ListMyTeamsRequest)(nil),                       // 0: user.ListMyTeamsRequest
	(*MyTeam)(nil),                                   // 1: user.MyTeam
	(*ListMyTeamsResponse)(nil),                      // 2: user.ListMyTeamsResponse
	(*BatchGetConversationDisplayNamesRequest)(nil),  // 3: user.BatchGetConversationDisplayNamesRequest
	(*ConversationDisplayName)(nil),                  // 4: user.ConversationDisplayName
	(*BatchGetConversationDisplayNamesResponse)(nil), // 5: user.BatchGetConversationDisplayNamesResponse
	(*LeaveTeamRequest)(nil),                         // 6: user.LeaveTeamRequest
	(*GetTeamLeaveOperationRequest)(nil),             // 7: user.GetTeamLeaveOperationRequest
	(*TeamLeaveOperationResponse)(nil),               // 8: user.TeamLeaveOperationResponse
	(*ResolveTeamMemberRequest)(nil),                 // 9: user.ResolveTeamMemberRequest
	(*ResolveTeamMemberResponse)(nil),                // 10: user.ResolveTeamMemberResponse
	(*CheckTeamMemberRequest)(nil),                   // 11: user.CheckTeamMemberRequest
	(*CheckTeamMemberResponse)(nil),                  // 12: user.CheckTeamMemberResponse
	(*CheckTeamMemberByIDRequest)(nil),               // 13: user.CheckTeamMemberByIDRequest
	(*CheckTeamMemberByIDResponse)(nil),              // 14: user.CheckTeamMemberByIDResponse
	(*AuthorizeTeamGroupCreationRequest)(nil),        // 15: user.AuthorizeTeamGroupCreationRequest
	(*AuthorizeTeamGroupCreationResponse)(nil),       // 16: user.AuthorizeTeamGroupCreationResponse
	(*SetTeamMemberRoleRequest)(nil),                 // 17: user.SetTeamMemberRoleRequest
	(*SetTeamMemberRoleResponse)(nil),                // 18: user.SetTeamMemberRoleResponse
	(*ListTeamMembersRequest)(nil),                   // 19: user.ListTeamMembersRequest
	(*TeamMember)(nil),                               // 20: user.TeamMember
	(*ListTeamMembersResponse)(nil),                  // 21: user.ListTeamMembersResponse
	(*AddTeamMemberRequest)(nil),                     // 22: user.AddTeamMemberRequest
	(*AddTeamMemberResponse)(nil),                    // 23: user.AddTeamMemberResponse
	(*CreateTeamRequest)(nil),                        // 24: user.CreateTeamRequest
	(*CreateTeamResponse)(nil),                       // 25: user.CreateTeamResponse
	(*GetMyInfoRequest)(nil),                         // 26: user.GetMyInfoRequest
	(*LoginRequest)(nil),                             // 27: user.LoginRequest
	(*LoginResponse)(nil),                            // 28: user.LoginResponse
	(*RegisterRequest)(nil),                          // 29: user.RegisterRequest
	(*RegisterResponse)(nil),                         // 30: user.RegisterResponse
	(*GetUserInfoRequest)(nil),                       // 31: user.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),                      // 32: user.GetUserInfoResponse
}
var file_user_proto_depIdxs = []int32{
	1,  // 0: user.ListMyTeamsResponse.teams:type_name -> user.MyTeam
	4,  // 1: user.BatchGetConversationDisplayNamesResponse.users:type_name -> user.ConversationDisplayName
	20, // 2: user.ResolveTeamMemberResponse.candidates:type_name -> user.TeamMember
	20, // 3: user.ListTeamMembersResponse.members:type_name -> user.TeamMember
	31, // 4: user.User.GetUserInfo:input_type -> user.GetUserInfoRequest
	26, // 5: user.User.GetMyInfo:input_type -> user.GetMyInfoRequest
	27, // 6: user.User.Login:input_type -> user.LoginRequest
	29, // 7: user.User.Register:input_type -> user.RegisterRequest
	24, // 8: user.User.CreateTeam:input_type -> user.CreateTeamRequest
	22, // 9: user.User.AddTeamMember:input_type -> user.AddTeamMemberRequest
	19, // 10: user.User.ListTeamMembers:input_type -> user.ListTeamMembersRequest
	17, // 11: user.User.SetTeamMemberRole:input_type -> user.SetTeamMemberRoleRequest
	15, // 12: user.User.AuthorizeTeamGroupCreation:input_type -> user.AuthorizeTeamGroupCreationRequest
	11, // 13: user.User.CheckTeamMember:input_type -> user.CheckTeamMemberRequest
	13, // 14: user.User.CheckTeamMemberByID:input_type -> user.CheckTeamMemberByIDRequest
	9,  // 15: user.User.ResolveTeamMember:input_type -> user.ResolveTeamMemberRequest
	6,  // 16: user.User.LeaveTeam:input_type -> user.LeaveTeamRequest
	7,  // 17: user.User.GetTeamLeaveOperation:input_type -> user.GetTeamLeaveOperationRequest
	0,  // 18: user.User.ListMyTeams:input_type -> user.ListMyTeamsRequest
	3,  // 19: user.User.BatchGetConversationDisplayNames:input_type -> user.BatchGetConversationDisplayNamesRequest
	32, // 20: user.User.GetUserInfo:output_type -> user.GetUserInfoResponse
	32, // 21: user.User.GetMyInfo:output_type -> user.GetUserInfoResponse
	28, // 22: user.User.Login:output_type -> user.LoginResponse
	30, // 23: user.User.Register:output_type -> user.RegisterResponse
	25, // 24: user.User.CreateTeam:output_type -> user.CreateTeamResponse
	23, // 25: user.User.AddTeamMember:output_type -> user.AddTeamMemberResponse
	21, // 26: user.User.ListTeamMembers:output_type -> user.ListTeamMembersResponse
	18, // 27: user.User.SetTeamMemberRole:output_type -> user.SetTeamMemberRoleResponse
	16, // 28: user.User.AuthorizeTeamGroupCreation:output_type -> user.AuthorizeTeamGroupCreationResponse
	12, // 29: user.User.CheckTeamMember:output_type -> user.CheckTeamMemberResponse
	14, // 30: user.User.CheckTeamMemberByID:output_type -> user.CheckTeamMemberByIDResponse
	10, // 31: user.User.ResolveTeamMember:output_type -> user.ResolveTeamMemberResponse
	8,  // 32: user.User.LeaveTeam:output_type -> user.TeamLeaveOperationResponse
	8,  // 33: user.User.GetTeamLeaveOperation:output_type -> user.TeamLeaveOperationResponse
	2,  // 34: user.User.ListMyTeams:output_type -> user.ListMyTeamsResponse
	5,  // 35: user.User.BatchGetConversationDisplayNames:output_type -> user.BatchGetConversationDisplayNamesResponse
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
